import type { CcrQuestion, CcrDomain, CcrRespondentType } from '@/types';

export const DOMAINS: CcrDomain[] = [
  { key: 'identity', label: 'Personal Identity & Self-Awareness', questionIds: [] },
  { key: 'academic', label: 'Academic Habits', questionIds: [] },
  { key: 'character', label: 'Character & Integrity', questionIds: [] },
  { key: 'emotional', label: 'Emotional Wellbeing', questionIds: [] },
  { key: 'social', label: 'Relationships & Social Skills', questionIds: [] },
  { key: 'family', label: 'Family & Home Environment', questionIds: [] },
  { key: 'digital', label: 'Digital Lifestyle', questionIds: [] },
  { key: 'faith', label: 'Faith & Values', questionIds: [] },
  { key: 'leadership', label: 'Leadership & Responsibility', questionIds: [] },
  { key: 'dreams', label: 'Dreams & Future', questionIds: [] },
];

export const DOMAIN_LABELS: Record<string, string> = {};
for (const d of DOMAINS) { DOMAIN_LABELS[d.key] = d.label; }

const D = DOMAIN_LABELS;

export const STUDENT_QUESTIONS: CcrQuestion[] = [
  { id: 'S_Q1', text: 'I know what I am good at.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity, notes: 'Optional comment: S_Q1_comment - "What are you good at?"' },
  { id: 'S_Q1_comment', text: 'What are you good at?', type: 'open_text', domain: 'identity', domainLabel: D.identity, maxLength: 250, required: false },
  { id: 'S_Q2', text: 'I know the areas where I need to improve.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity, notes: 'Optional comment: S_Q2_comment - "What would you like to improve?"' },
  { id: 'S_Q2_comment', text: 'What would you like to improve?', type: 'open_text', domain: 'identity', domainLabel: D.identity, maxLength: 250, required: false },
  { id: 'S_Q3', text: 'When someone corrects me, I usually...', type: 'single_choice', domain: 'identity', domainLabel: D.identity, options: ['Listen and learn', 'Listen but feel upset', 'Ignore it', 'Argue', 'It depends'] },
  { id: 'S_Q4', text: 'I feel confident speaking in front of people.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'S_Q5', text: 'Choose up to three words that describe you.', type: 'multi_choice', domain: 'identity', domainLabel: D.identity, options: ['Friendly', 'Quiet', 'Curious', 'Creative', 'Hardworking', 'Helpful', 'Funny', 'Shy', 'Confident', 'Organized', 'Emotional', 'Leader', 'Independent', 'Caring', 'Patient'], maxSelect: 3 },
  { id: 'S_Q6', text: 'When I make a mistake...', type: 'single_choice', domain: 'identity', domainLabel: D.identity, options: ['I admit it', 'I try to correct it', 'I hide it', 'I blame others', 'It depends'] },
  { id: 'S_Q7', text: 'How happy are you with yourself?', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'S_Q8', text: 'What makes you happiest? Choose up to three.', type: 'multi_choice', domain: 'identity', domainLabel: D.identity, options: ['Family', 'Friends', 'School', 'Sports', 'Reading', 'Gaming', 'Technology', 'Religion', 'Helping others', 'Learning', 'Arts', 'Other'], maxSelect: 3 },
  { id: 'S_Q8_other', text: 'Other - please specify:', type: 'open_text', domain: 'identity', domainLabel: D.identity, maxLength: 250, required: false },
  { id: 'S_Q9', text: 'If you could change one thing about yourself, what would it be?', type: 'open_text', domain: 'identity', domainLabel: D.identity, maxLength: 2000 },
  { id: 'S_Q10', text: 'Complete this sentence. "I become my best self when..."', type: 'open_text', domain: 'identity', domainLabel: D.identity, maxLength: 2000 },
  { id: 'S_Q11', text: 'I understand my strengths and can explain them to others.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'S_Q12', text: 'I set personal goals and try to achieve them.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'S_Q13', text: 'I complete my homework before the deadline.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'S_Q14', text: 'When I don\'t understand something in class, I...', type: 'single_choice', domain: 'academic', domainLabel: D.academic, options: ['Ask the teacher', 'Ask a friend', 'Search online', 'Wait until later', 'Ignore it'] },
  { id: 'S_Q15', text: 'I revise my lessons even when there is no test.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'S_Q16', text: 'The main reasons I don\'t study. Choose up to three.', type: 'multi_choice', domain: 'academic', domainLabel: D.academic, options: ['Phone', 'Friends', 'Television', 'Gaming', 'I get tired', 'I don\'t understand', 'I forget', 'No quiet place', 'Not interested', 'Other'], maxSelect: 3 },
  { id: 'S_Q16_other', text: 'Other reason for not studying:', type: 'open_text', domain: 'academic', domainLabel: D.academic, maxLength: 250, required: false },
  { id: 'S_Q17', text: 'How many hours do you study after school?', type: 'single_choice', domain: 'academic', domainLabel: D.academic, options: ['<30 minutes', '30-60 minutes', '1-2 hours', 'More than 2 hours'] },
  { id: 'S_Q18', text: 'My favourite subjects are (select up to three).', type: 'multi_choice', domain: 'academic', domainLabel: D.academic, options: ['English', 'Mathematics', 'Science', 'Social Studies', 'Arabic', 'Islamic Studies', 'ICT', 'French', 'Art', 'Music', 'Physical Education'], maxSelect: 3 },
  { id: 'S_Q19', text: 'The subjects I find most difficult (select up to three).', type: 'multi_choice', domain: 'academic', domainLabel: D.academic, options: ['English', 'Mathematics', 'Science', 'Social Studies', 'Arabic', 'Islamic Studies', 'ICT', 'French', 'Art', 'Music', 'Physical Education'], maxSelect: 3 },
  { id: 'S_Q20', text: 'When my results are poor, I...', type: 'single_choice', domain: 'academic', domainLabel: D.academic, options: ['Work harder', 'Ask for help', 'Feel discouraged', 'Ignore it', 'Blame others'] },
  { id: 'S_Q21', text: 'How prepared do you feel before examinations?', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'S_Q22', text: 'I use a study plan or timetable.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'S_Q23', text: 'I seek feedback on my work and act on it.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'S_Q24', text: 'If your academic performance could improve this year, what would help you most?', type: 'open_text', domain: 'academic', domainLabel: D.academic, maxLength: 2000 },
  { id: 'S_Q25', text: 'I can concentrate in class despite distractions.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'S_Q26', text: 'I manage my time well for school tasks.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'S_Q27', text: 'I tell the truth even when it is difficult.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'S_Q28', text: 'I keep my promises.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'S_Q29', text: 'I return things that are not mine.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'S_Q30', text: 'I apologize when I am wrong.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'S_Q31', text: 'I respect school rules.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'S_Q32', text: 'If nobody is watching me, I still do the right thing.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'S_Q33', text: 'If I damage something, I report it.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'S_Q34', text: 'When friends encourage me to do something wrong, I...', type: 'single_choice', domain: 'character', domainLabel: D.character, options: ['Refuse', 'Sometimes refuse', 'Follow them', 'Depends'] },
  { id: 'S_Q35', text: 'You find ₦10,000 on the school field. What would you most likely do?', type: 'single_choice', domain: 'character', domainLabel: D.character, options: ['Leave it', 'Take to a teacher', 'Look for the owner', 'Keep it', 'Ask friends'] },
  { id: 'S_Q35_comment', text: 'Optional comment about the scenario:', type: 'open_text', domain: 'character', domainLabel: D.character, maxLength: 250, required: false },
  { id: 'S_Q36', text: 'I feel stressed about schoolwork.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional, notes: 'Higher = more stress (reverse when computing wellbeing)' },
  { id: 'S_Q37', text: 'I get angry easily.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'S_Q38', text: 'I feel lonely at school.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'S_Q39', text: 'I can ask for help when I need it.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'S_Q40', text: 'I can manage disappointment well.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'S_Q41', text: 'I feel confident about my future.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'S_Q42', text: 'I sleep well most nights.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'S_Q43', text: 'I feel accepted by my classmates.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'S_Q44', text: 'When under pressure, I cope effectively.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'S_Q45', text: 'I worry about being judged by others.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'S_Q46', text: 'I can calm myself when upset.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'S_Q47', text: 'I have someone at school I can talk to about personal problems.', type: 'single_choice', domain: 'emotional', domainLabel: D.emotional, options: ['Yes', 'No', 'Not sure'] },
  { id: 'S_Q47_contact', text: 'If yes, who?', type: 'open_text', domain: 'emotional', domainLabel: D.emotional, maxLength: 250, required: false },
  { id: 'S_Q48', text: 'If there is one thing the school should know about your wellbeing, what is it?', type: 'open_text', domain: 'emotional', domainLabel: D.emotional, maxLength: 2000, required: true },
  { id: 'S_Q49', text: 'I have close friends at school.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'S_Q50', text: 'I treat others with respect.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'S_Q51', text: 'I can resolve conflicts peacefully.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'S_Q52', text: 'I have seen or experienced bullying at school.', type: 'single_choice', domain: 'social', domainLabel: D.social, options: ['Yes - experienced', 'Yes - witnessed', 'No', 'Prefer not to say'] },
  { id: 'S_Q52_comment', text: 'Optional comment about bullying:', type: 'open_text', domain: 'social', domainLabel: D.social, maxLength: 250, required: false },
  { id: 'S_Q53', text: 'I help others when they need it.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'S_Q54', text: 'I forgive people who hurt me.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'S_Q55', text: 'I work well in teams.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'S_Q56', text: 'I communicate my ideas clearly.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'S_Q57', text: 'I listen to others.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'S_Q58', text: 'I can understand how others feel (empathy).', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'S_Q59', text: 'My parents/caregivers encourage my schoolwork.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'S_Q60', text: 'There is a quiet place at home where I can study.', type: 'single_choice', domain: 'family', domainLabel: D.family, options: ['Always', 'Often', 'Sometimes', 'Rarely', 'Never'] },
  { id: 'S_Q61', text: 'I have responsibilities at home (chores).', type: 'single_choice', domain: 'family', domainLabel: D.family, options: ['None', 'A few', 'Several', 'Many'] },
  { id: 'S_Q62', text: 'My parents talk to me about my day at school.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'S_Q63', text: 'I feel safe at home.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'S_Q64', text: 'My family supports my goals.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'S_Q65', text: 'My parents check my homework.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'S_Q66', text: 'If there is anything at home the school should know, what is it?', type: 'open_text', domain: 'family', domainLabel: D.family, maxLength: 2000, required: false },
  { id: 'S_Q67', text: 'How many hours per day do you usually use a phone or tablet (not schoolwork)?', type: 'single_choice', domain: 'digital', domainLabel: D.digital, options: ['<1h', '1-2h', '2-4h', '4-6h', '>6h'] },
  { id: 'S_Q68', text: 'I often use my phone at night when I should be sleeping.', type: 'scale_1_5', domain: 'digital', domainLabel: D.digital },
  { id: 'S_Q69', text: 'I play online games regularly.', type: 'scale_1_5', domain: 'digital', domainLabel: D.digital },
  { id: 'S_Q70', text: 'I feel distracted by social media during study time.', type: 'scale_1_5', domain: 'digital', domainLabel: D.digital },
  { id: 'S_Q71', text: 'I have experienced online bullying.', type: 'single_choice', domain: 'digital', domainLabel: D.digital, options: ['Yes', 'No'] },
  { id: 'S_Q71_comment', text: 'Optional comment about online bullying:', type: 'open_text', domain: 'digital', domainLabel: D.digital, maxLength: 250, required: false },
  { id: 'S_Q72', text: 'I know how to stay safe online.', type: 'scale_1_5', domain: 'digital', domainLabel: D.digital },
  { id: 'S_Q73', text: 'Technology helps my learning.', type: 'scale_1_5', domain: 'digital', domainLabel: D.digital },
  { id: 'S_Q74', text: 'I sometimes feel addicted to my screen.', type: 'scale_1_5', domain: 'digital', domainLabel: D.digital },
  { id: 'S_Q75', text: 'I understand the basic teachings and stories of Islam (Prophets, the Quran, and core beliefs).', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'S_Q75_comment', text: 'Optional comment:', type: 'open_text', domain: 'faith', domainLabel: D.faith, maxLength: 250, required: false },
  { id: 'S_Q76', text: 'I perform the five daily prayers (Salah) at the times prescribed by Islam.', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'S_Q77', text: 'When I perform Salah or other religious practices, I concentrate and perform them properly (khushu).', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'S_Q77_comment', text: 'Optional comment:', type: 'open_text', domain: 'faith', domainLabel: D.faith, maxLength: 250, required: false },
  { id: 'S_Q78', text: 'I try to follow my parents\' guidance about practising Islam.', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'S_Q79', text: 'I obey my parents\' instructions at home.', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'S_Q80', text: 'I show respect and obedience to my teachers at school.', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'S_Q81', text: 'I take initiative in group activities.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'S_Q82', text: 'I volunteer for leadership roles.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'S_Q83', text: 'I help classmates who are struggling.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'S_Q84', text: 'I can organize tasks or events.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'S_Q85', text: 'I speak confidently in front of groups.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'S_Q86', text: 'I make decisions responsibly.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'S_Q87', text: 'Others rely on me to finish tasks.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'S_Q88', text: 'I accept responsibility for my mistakes.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'S_Q89', text: 'I motivate others to work harder.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'S_Q90', text: 'If you were to lead a school activity, what would it be?', type: 'open_text', domain: 'leadership', domainLabel: D.leadership, maxLength: 2000 },
  { id: 'S_Q91', text: 'I have a clear idea of what career I would like.', type: 'scale_1_5', domain: 'dreams', domainLabel: D.dreams },
  { id: 'S_Q92', text: 'I have role models I try to learn from.', type: 'scale_1_5', domain: 'dreams', domainLabel: D.dreams },
  { id: 'S_Q93', text: 'I set goals for the next five years.', type: 'scale_1_5', domain: 'dreams', domainLabel: D.dreams },
  { id: 'S_Q94', text: 'I know what skills I need for my future career.', type: 'scale_1_5', domain: 'dreams', domainLabel: D.dreams },
  { id: 'S_Q95', text: 'My biggest challenge in achieving my goals is...', type: 'open_text', domain: 'dreams', domainLabel: D.dreams, maxLength: 2000 },
  { id: 'S_Q96', text: 'My biggest dream is...', type: 'open_text', domain: 'dreams', domainLabel: D.dreams, maxLength: 2000 },
  { id: 'S_Q97', text: 'I want to contribute to my community in this way...', type: 'open_text', domain: 'dreams', domainLabel: D.dreams, maxLength: 2000 },
  { id: 'S_Q98', text: 'I have a message to my future self.', type: 'open_text', domain: 'dreams', domainLabel: D.dreams, maxLength: 2000 },
  { id: 'S_Q99', text: 'How hopeful are you about your future?', type: 'scale_1_5', domain: 'dreams', domainLabel: D.dreams },
  { id: 'S_Q100', text: 'If there is one thing the school should know about you that has not been asked, what would it be?', type: 'open_text', domain: 'dreams', domainLabel: D.dreams, maxLength: 2000, required: true },
];

export const FATHER_QUESTIONS: CcrQuestion[] = [
  { id: 'F_Q1', text: 'My child accepts correction without becoming defensive.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'F_Q2', text: 'My child completes homework without repeated reminders.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'F_Q3', text: 'My child uses technology responsibly.', type: 'scale_1_5', domain: 'digital', domainLabel: D.digital },
  { id: 'F_Q4', text: 'My child tells the truth even when it is difficult.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'F_Q5', text: 'My child shows respect to adults and siblings.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'F_Q6', text: 'My child talks to us about problems.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'F_Q7', text: 'I know my child\'s close friends.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'F_Q8', text: 'I believe my child is developing strong moral values.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'F_Q9', text: 'My child sleeps well at night.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'F_Q10', text: 'My child is happy with school.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'F_Q11', text: 'My child is able to manage anger or frustration.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'F_Q12', text: 'My child shows leadership at home or school.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'F_Q13', text: 'My child respects school rules.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'F_Q14', text: 'My child shows empathy towards others.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'F_Q15', text: 'My child completes chores/responsibilities at home.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'F_Q16', text: 'My child studies at home regularly.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'F_Q17', text: 'My child is punctual (arrives on time).', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'F_Q18', text: 'My child participates in extracurricular activities.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'F_Q19', text: 'My child feels safe at home.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'F_Q20', text: 'My child has a quiet place to study.', type: 'single_choice', domain: 'family', domainLabel: D.family, options: ['Always', 'Often', 'Sometimes', 'Rarely', 'Never'] },
  { id: 'F_Q21', text: 'I discuss my child\'s progress with teachers.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'F_Q22', text: 'My child shows honesty about schoolwork.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'F_Q23', text: 'My child is resilient when faced with setbacks.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'F_Q24', text: 'My child has good peer relationships.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'F_Q25', text: 'My child engages in excessive screen time.', type: 'scale_1_5', domain: 'digital', domainLabel: D.digital },
  { id: 'F_Q26', text: 'My child displays signs of anxiety or worry.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'F_Q27', text: 'My child shares family concerns with us.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'F_Q28', text: 'My child follows directions at home.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'F_Q29', text: 'My child shows interest in future goals.', type: 'scale_1_5', domain: 'dreams', domainLabel: D.dreams },
  { id: 'F_Q30', text: 'My child helps others without being asked.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'F_Q31', text: 'My child apologizes when wrong.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'F_Q32', text: 'I am concerned about my child\'s safety at school.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'F_Q33', text: 'My child is truthful about their activities.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'F_Q34', text: 'My child is organized with school materials.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'F_Q35', text: 'My child is motivated by praise or rewards.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'F_Q36', text: 'My child can work independently.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'F_Q37', text: 'My child handles peer pressure well.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'F_Q38', text: 'My child communicates well with adults.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'F_Q39', text: 'My child shows good moral judgement.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'F_Q40', text: 'I would recommend additional support (counselor) for my child.', type: 'single_choice', domain: 'emotional', domainLabel: D.emotional, options: ['Yes', 'No', 'Maybe'] },
  { id: 'F_Q40_comment', text: 'Optional comment about additional support:', type: 'open_text', domain: 'emotional', domainLabel: D.emotional, maxLength: 250, required: false },
  { id: 'F_Q41', text: 'If there is one thing the school should know about my child, it is...', type: 'open_text', domain: 'identity', domainLabel: D.identity, maxLength: 2000, required: true },
  { id: 'F_Q42', text: 'My child practices Islam at home (knowledge/routines).', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'F_Q43', text: 'My child performs the five daily prayers at expected times.', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'F_Q44', text: 'My child prays with focus and sincerity (khushu).', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'F_Q45', text: 'My child follows family rules about religion.', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'F_Q46', text: 'My child shows obedience to parents at home.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'F_Q47', text: 'My child shows respect for teachers at school.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'F_Q48', text: 'I talk with my child about Islamic teachings.', type: 'single_choice', domain: 'faith', domainLabel: D.faith, options: ['Often', 'Sometimes', 'Rarely', 'Never'] },
  { id: 'F_Q49', text: 'My child behaves respectfully during school religious activities.', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'F_Q50', text: 'My child is punctual to school and activities.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'F_Q51', text: 'My child is honest about school behaviour.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'F_Q52', text: 'My child has stable friendships.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'F_Q53', text: 'My child responds well to teacher correction.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'F_Q54', text: 'My child shows responsibility for schoolwork.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'F_Q55', text: 'My child shares problems with family.', type: 'scale_1_5', domain: 'family', domainLabel: D.family },
  { id: 'F_Q56', text: 'My child expresses gratitude and politeness.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'F_Q57', text: 'My child shows kindness to others.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'F_Q58', text: 'My child displays good emotional control.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'F_Q59', text: 'My child seeks help when needed.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'F_Q60', text: 'My child demonstrates consistent moral behaviour across settings.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
];

export const MOTHER_QUESTIONS: CcrQuestion[] = FATHER_QUESTIONS.map((q, i) => ({
  ...q,
  id: q.id.replace('F_', 'M_'),
}));

export const TEACHER_QUESTIONS: CcrQuestion[] = [
  { id: 'T_Q1', text: 'Arrives prepared for class.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q2', text: 'Participates actively in lessons.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q3', text: 'Completes assignments on time.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q4', text: 'Responds positively to feedback.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'T_Q5', text: 'Shows respect to peers and staff.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q6', text: 'Demonstrates self-control during lessons.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'T_Q7', text: 'Works well in groups.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q8', text: 'Shows leadership when appropriate.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'T_Q9', text: 'Perseveres through challenging tasks.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q10', text: 'Contributes positively to the classroom environment.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q11', text: 'Demonstrates academic potential beyond current performance.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q12', text: 'Shows signs of emotional distress.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional, notes: 'Higher = more distress (flag if >3)' },
  { id: 'T_Q13', text: 'Is often late to class.', type: 'single_choice', domain: 'academic', domainLabel: D.academic, options: ['Never', 'Rarely', 'Sometimes', 'Often'] },
  { id: 'T_Q14', text: 'Is frequently absent.', type: 'single_choice', domain: 'academic', domainLabel: D.academic, options: ['Never', 'Rarely', 'Sometimes', 'Often'] },
  { id: 'T_Q15', text: 'Has strong peer relationships.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q16', text: 'Is respectful to school property.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'T_Q17', text: 'Shows improvement over recent term.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q18', text: 'Responds well to teacher correction.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'T_Q19', text: 'Engages in leadership in the classroom.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'T_Q20', text: 'Completes class tests and quizzes to potential.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q21', text: 'Shows empathy to classmates.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q22', text: 'Is easily distracted by digital devices.', type: 'scale_1_5', domain: 'digital', domainLabel: D.digital, notes: 'Higher = more distracted' },
  { id: 'T_Q23', text: 'Demonstrates honesty in assessments.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'T_Q24', text: 'Helps other students when needed.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q25', text: 'Shows resilience after setbacks.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'T_Q26', text: 'Maintains focus during lessons.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q27', text: 'Interacts respectfully with staff.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q28', text: 'Needs additional support to meet learning objectives.', type: 'single_choice', domain: 'academic', domainLabel: D.academic, options: ['None', 'Some', 'Significant'] },
  { id: 'T_Q29', text: 'Shows leadership in extracurricular activities.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'T_Q30', text: 'Is cooperative during group tasks.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q31', text: 'Demonstrates positive behaviour consistently.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'T_Q32', text: 'Is respectful in conversations with adults.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q33', text: 'Shows initiative in class activities.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'T_Q34', text: 'Manages classroom emotions well.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'T_Q35', text: 'Completes homework assigned by teachers.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q36', text: 'Demonstrates problem-solving skills.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q37', text: 'Is respectful during school religious activities.', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'T_Q38', text: 'Shows appropriate dress and appearance.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'T_Q39', text: 'Communicates concerns to school staff.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'T_Q40', text: 'Encourages classmates positively.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q41', text: 'Demonstrates curiosity and asks questions.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q42', text: 'Shows consistency across different classes.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'T_Q43', text: 'Follows school rules about using devices.', type: 'scale_1_5', domain: 'digital', domainLabel: D.digital },
  { id: 'T_Q44', text: 'Is cooperative with classmates from diverse backgrounds.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q45', text: 'Shows progress in social skills.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q46', text: 'Demonstrates self-motivation.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'T_Q47', text: 'Displays appropriate behaviour during assessments.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'T_Q48', text: 'Is respectful during assemblies and prayers.', type: 'scale_1_5', domain: 'faith', domainLabel: D.faith },
  { id: 'T_Q49', text: 'Shows leadership potential.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'T_Q50', text: 'Completes practical tasks reliably.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q51', text: 'Shows initiative beyond classroom requirements.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'T_Q52', text: 'Is respectful when given feedback.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'T_Q53', text: 'Maintains good concentration during tests.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q54', text: 'Demonstrates appropriate peer leadership.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'T_Q55', text: 'Is mindful of classroom safety.', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'T_Q56', text: 'Shows respect to substitute teachers.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'T_Q57', text: 'Adapts well to changes in routine.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'T_Q58', text: 'Needs encouragement to participate.', type: 'scale_1_5', domain: 'identity', domainLabel: D.identity },
  { id: 'T_Q59', text: 'Is able to follow multi-step instructions.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'T_Q60', text: 'If there is one thing the school should know about this child that has not been asked, what would it be?', type: 'open_text', domain: 'identity', domainLabel: D.identity, maxLength: 2000, required: true },
  { id: 'ST_Q1', text: 'Student\'s subject-specific preparedness for class.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q2', text: 'Completes homework for this subject on time.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q3', text: 'Participates meaningfully during lessons in this subject.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q4', text: 'Demonstrates conceptual understanding.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q5', text: 'Applies feedback to improve performance.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q6', text: 'Collaborates effectively in subject group work.', type: 'scale_1_5', domain: 'social', domainLabel: D.social },
  { id: 'ST_Q7', text: 'Shows curiosity and asks questions.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q8', text: 'Shows steady improvement in this subject.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q9', text: 'Is distracted by digital devices during lessons.', type: 'scale_1_5', domain: 'digital', domainLabel: D.digital },
  { id: 'ST_Q10', text: 'Is punctual to this class.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q11', text: 'Is honest in assessments (no cheating observed).', type: 'scale_1_5', domain: 'character', domainLabel: D.character },
  { id: 'ST_Q12', text: 'Demonstrates leadership in group tasks.', type: 'scale_1_5', domain: 'leadership', domainLabel: D.leadership },
  { id: 'ST_Q13', text: 'Works well on practical tasks (where applicable).', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q14', text: 'Shows resilience after poor performance.', type: 'scale_1_5', domain: 'emotional', domainLabel: D.emotional },
  { id: 'ST_Q15', text: 'Shows good written communication.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q16', text: 'Shows good oral communication.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q17', text: 'Uses study resources appropriately.', type: 'scale_1_5', domain: 'academic', domainLabel: D.academic },
  { id: 'ST_Q18', text: 'Requires additional support to meet learning objectives.', type: 'single_choice', domain: 'academic', domainLabel: D.academic, options: ['None', 'Some', 'Significant'] },
  { id: 'ST_Q19', text: 'If there is one thing about this student in this subject the school should know, it is...', type: 'open_text', domain: 'academic', domainLabel: D.academic, maxLength: 2000, required: false },
  { id: 'ST_Q20', text: 'Would you recommend an intervention for this subject?', type: 'single_choice', domain: 'academic', domainLabel: D.academic, options: ['Yes', 'No'] },
  { id: 'ST_Q20_comment', text: 'Optional comment about intervention:', type: 'open_text', domain: 'academic', domainLabel: D.academic, maxLength: 250, required: false },
];

export const QUESTIONS_BY_TYPE: Record<CcrRespondentType, CcrQuestion[]> = {
  student: STUDENT_QUESTIONS,
  father: FATHER_QUESTIONS,
  mother: MOTHER_QUESTIONS,
  teacher: TEACHER_QUESTIONS,
  subject_teacher: TEACHER_QUESTIONS,
};

export function getQuestionsByType(type: CcrRespondentType): CcrQuestion[] {
  if (type === 'subject_teacher') {
    return TEACHER_QUESTIONS.filter(q => q.id.startsWith('ST_'));
  }
  if (type === 'teacher') {
    return TEACHER_QUESTIONS.filter(q => q.id.startsWith('T_'));
  }
  return QUESTIONS_BY_TYPE[type] || [];
}

export function getDomainQuestions(type: CcrRespondentType, domainKey: string): CcrQuestion[] {
  return getQuestionsByType(type).filter(q => q.domain === domainKey);
}

export function getQuestionById(type: CcrRespondentType, questionId: string): CcrQuestion | undefined {
  return getQuestionsByType(type).find(q => q.id === questionId);
}
