-- This script disables Row-Level Security (RLS) on all tables to ensure that 
-- admins, teachers, and accountants can add, edit, and delete data without permission errors.
-- Run this in the Supabase SQL Editor.

ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE school_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE departments DISABLE ROW LEVEL SECURITY;
ALTER TABLE classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE subjects DISABLE ROW LEVEL SECURITY;
ALTER TABLE students DISABLE ROW LEVEL SECURITY;
ALTER TABLE staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE lessons DISABLE ROW LEVEL SECURITY;
ALTER TABLE quizzes DISABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE homework DISABLE ROW LEVEL SECURITY;
ALTER TABLE homework_submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE staff_attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE results DISABLE ROW LEVEL SECURITY;
ALTER TABLE behavioral_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE announcements DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE receipts DISABLE ROW LEVEL SECURITY;
ALTER TABLE id_cards DISABLE ROW LEVEL SECURITY;
ALTER TABLE entrance_exams DISABLE ROW LEVEL SECURITY;
ALTER TABLE entrance_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE entrance_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE entrance_applications DISABLE ROW LEVEL SECURITY;
ALTER TABLE tests DISABLE ROW LEVEL SECURITY;
ALTER TABLE test_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE test_attempts DISABLE ROW LEVEL SECURITY;
ALTER TABLE teacher_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE teacher_evaluations DISABLE ROW LEVEL SECURITY;
ALTER TABLE student_performance DISABLE ROW LEVEL SECURITY;
ALTER TABLE class_performance DISABLE ROW LEVEL SECURITY;
ALTER TABLE student_risk_predictions DISABLE ROW LEVEL SECURITY;
ALTER TABLE prediction_features DISABLE ROW LEVEL SECURITY;
ALTER TABLE model_performance DISABLE ROW LEVEL SECURITY;
ALTER TABLE interventions DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE message_attachments DISABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE communication_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE communication_group_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE group_messages DISABLE ROW LEVEL SECURITY;

SELECT 'Row-Level Security has been successfully disabled for all tables.' as status;
