-- ============================================================================
-- CLEARPATH EDU HUB - PRIMARY SCIENCES & GENERAL KNOWLEDGE QUESTION BANK
-- ============================================================================
-- 100 challenging questions for PRIMARY level:
--   A) BASIC SCIENCE  (50 questions)
--   B) ISLAMIC STUDIES + GENERAL KNOWLEDGE (50 questions)
-- SAFE TO RE-RUN: Uses ON CONFLICT DO NOTHING
-- ============================================================================

-- ============================================================================
-- A) BASIC SCIENCE (50 challenging questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES

-- === Living Things (8 questions) ===
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Living Things', 'Characteristics', 'Which of the following is NOT a characteristic of all living things?', '{"Movement","Growth","Production of manufactured goods","Reproduction"}'::text[], 2, 'Production of manufactured goods is a human activity, not a characteristic of all living things. All living things move, grow, and reproduce.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Living Things', 'Classification', 'A scientist discovers a new organism that is unicellular, has a nucleus, and can move on its own. To which kingdom does it most likely belong?', '{"Plantae","Animalia","Protista","Fungi"}'::text[], 2, 'Protista includes unicellular organisms with a nucleus. Animals are multicellular, plants make their own food, fungi absorb nutrients.', 'MCQ', 3, true),
('BASIC SCIENCE', 'PRIMARY', 'VERY_HARD', 'Living Things', 'Cells', 'Which part of the cell is responsible for controlling all activities and is often called the "brain" of the cell?', '{"Cell wall","Cytoplasm","Nucleus","Cell membrane"}'::text[], 2, 'The nucleus controls all cell activities and contains genetic material (DNA). The cell wall provides structure, cytoplasm is where reactions happen, the membrane controls entry/exit.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Living Things', 'Habitat', 'A habitat where the soil is always waterlogged, with plants that have breathing roots, is most likely a:', '{"Desert","Rainforest","Mangrove swamp","Savanna"}'::text[], 2, 'Mangrove swamps have waterlogged soil, and mangrove trees have specialized breathing roots (pneumatophores) that stick out of the water to get oxygen.', 'MCQ', 3, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Living Things', 'Adaptation', 'Camels have long eyelashes, nostrils that can close, and humps that store fat. These features are adaptations for surviving in:', '{"Rainforests","Deserts","Mountains","Oceans"}'::text[], 1, 'These features help camels survive in hot, dry desert environments. The long eyelashes keep sand out, closable nostrils prevent sand inhalation, and humps store energy.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Living Things', 'Food Chains', 'In a food chain, which organism is always at the beginning?', '{"Primary consumer","Producer","Secondary consumer","Decomposer"}'::text[], 1, 'Producers (plants) are always at the beginning of a food chain because they make their own food through photosynthesis.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'VERY_HARD', 'Living Things', 'Ecosystem', 'If all the decomposers in a forest ecosystem suddenly disappeared, what would most likely happen?', '{"Plants would grow faster","The forest would flourish","Dead matter would pile up and nutrients would not be recycled","Animals would become herbivores"}'::text[], 2, 'Decomposers break down dead organisms and waste, returning nutrients to the soil. Without them, dead matter accumulates and nutrients become unavailable for new plant growth.', 'MCQ', 3, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Living Things', 'Life Cycles', 'Which stage follows the caterpillar in the life cycle of a butterfly?', '{"Egg","Adult butterfly","Pupa (chrysalis)","Larva"}'::text[], 2, 'The butterfly life cycle: Egg → Larva (caterpillar) → Pupa (chrysalis) → Adult butterfly.', 'MCQ', 2, true),

-- === Plants (6 questions) ===
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Plants', 'Photosynthesis', 'Which gas do plants absorb from the air during photosynthesis?', '{"Oxygen","Nitrogen","Carbon dioxide","Hydrogen"}'::text[], 2, 'Plants absorb carbon dioxide from the air and, using sunlight and water, convert it into glucose and oxygen through photosynthesis.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Plants', 'Seed Germination', 'Which of the following is NOT required for a seed to germinate?', '{"Water","Suitable temperature","Sunlight","Oxygen"}'::text[], 2, 'Most seeds can germinate in darkness; they do not need sunlight until they have grown leaves and need to photosynthesize. Water, warmth, and oxygen are essential.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'VERY_HARD', 'Plants', 'Transport', 'The tissue that transports water and minerals from the roots to the leaves in plants is called:', '{"Phloem","Xylem","Cambium","Epidermis"}'::text[], 1, 'Xylem transports water and minerals upward from roots to leaves. Phloem transports food (glucose) from leaves to other parts of the plant.', 'MCQ', 3, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Plants', 'Reproduction', 'The male part of a flower that produces pollen is called the:', '{"Stigma","Ovary","Stamen","Pistil"}'::text[], 2, 'The stamen is the male reproductive part, consisting of the anther (which produces pollen) and filament. The pistil is the female part.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Plants', 'Classification', 'Which of these plants reproduces by spores rather than seeds?', '{"Mango tree","Maize plant","Fern","Orange tree"}'::text[], 2, 'Ferns reproduce through spores found on the underside of their leaves. Mango, maize, and orange trees all reproduce through seeds.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Plants', 'Uses', 'The part of the cassava plant that is commonly eaten is the:', '{"Leaf","Fruit","Stem","Root"}'::text[], 3, 'Cassava is a root tuber. The swollen roots are harvested and processed into garri, fufu, tapioca, and other foods.', 'MCQ', 2, true),

-- === Animals (6 questions) ===
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Animals', 'Vertebrates', 'Which group of animals all have backbones?', '{"Insects, fish, birds","Fish, amphibians, reptiles, birds, mammals","Snails, worms, insects","Jellyfish, starfish, crabs"}'::text[], 1, 'Vertebrates are animals with backbones: fish, amphibians, reptiles, birds, and mammals. Insects, snails, worms, and jellyfish are invertebrates.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Animals', 'Mammals', 'Which characteristic is unique to mammals and not found in any other animal group?', '{"Warm-blooded","Live birth","Produce milk for young","Have hair/fur"}'::text[], 2, 'While many mammals have fur and are warm-blooded, producing milk to feed young is the defining characteristic unique to all mammals.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Animals', 'Metamorphosis', 'Which of these animals undergoes complete metamorphosis?', '{"Grasshopper","Frog","Dragonfly","Cockroach"}'::text[], 1, 'Frogs undergo complete metamorphosis: egg → tadpole (larva) → froglet → adult frog. The others listed undergo incomplete metamorphosis.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'VERY_HARD', 'Animals', 'Behavior', 'The seasonal movement of animals from one region to another, often to find food or breeding grounds, is called:', '{"Hibernation","Migration","Estivation","Camouflage"}'::text[], 1, 'Migration is the seasonal movement of animals. Hibernation is winter sleep, estivation is summer sleep, and camouflage is blending into the environment.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Animals', 'Invertebrates', 'An earthworm belongs to which group of invertebrates?', '{"Arthropods","Mollusks","Annelids","Echinoderms"}'::text[], 2, 'Earthworms are annelids (segmented worms). Arthropods have jointed legs, mollusks have soft bodies often with shells, echinoderms have spiny skin.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Animals', 'Adaptation', 'A fishs gills are adapted for:', '{"Swimming fast","Extracting oxygen from water","Capturing prey","Digesting food"}'::text[], 1, 'Gills are specialized organs that extract dissolved oxygen from water as water flows over the gill filaments.', 'MCQ', 2, true),

-- === Human Body (6 questions) ===
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Human Body', 'Digestive System', 'In which organ of the digestive system does most nutrient absorption take place?', '{"Stomach","Large intestine","Small intestine","Mouth"}'::text[], 2, 'The small intestine is where most nutrients from digested food are absorbed into the bloodstream through its villi.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Human Body', 'Circulatory System', 'Which blood vessels carry blood away from the heart?', '{"Veins","Arteries","Capillaries","Venules"}'::text[], 1, 'Arteries carry oxygenated blood away from the heart (except the pulmonary artery). Veins carry blood back to the heart.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Human Body', 'Respiratory System', 'The tiny air sacs in the lungs where gas exchange occurs are called:', '{"Bronchi","Trachea","Alveoli","Bronchioles"}'::text[], 2, 'Alveoli are tiny air sacs surrounded by capillaries where oxygen enters the blood and carbon dioxide leaves.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'VERY_HARD', 'Human Body', 'Nervous System', 'Which part of the brain controls balance and coordination of movement?', '{"Cerebrum","Cerebellum","Medulla oblongata","Hypothalamus"}'::text[], 1, 'The cerebellum controls balance, coordination, and fine motor movements. The cerebrum handles thinking, the medulla controls automatic functions like breathing.', 'MCQ', 3, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Human Body', 'Skeletal System', 'What is the primary function of the rib cage?', '{"Help us bend forward","Protect the heart and lungs","Allow the arms to move","Store calcium"}'::text[], 1, 'The rib cage forms a protective barrier around vital organs, especially the heart and lungs.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Human Body', 'Sense Organs', 'Which part of the eye contains cells that detect light and color?', '{"Cornea","Iris","Retina","Lens"}'::text[], 2, 'The retina at the back of the eye contains light-sensitive cells (rods and cones) that detect light and color and send signals to the brain.', 'MCQ', 2, true),

-- === Health & Hygiene (4 questions) ===
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Health', 'Nutrition', 'A deficiency of iron in the diet is most likely to cause:', '{"Scurvy","Anemia","Rickets","Kwashiorkor"}'::text[], 1, 'Iron deficiency causes anemia (reduced red blood cells). Scurvy is from vitamin C deficiency, rickets from vitamin D, and kwashiorkor from protein deficiency.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'VERY_HARD', 'Health', 'Diseases', 'Malaria is caused by a parasite transmitted through the bite of an infected:', '{"Housefly","Tsetse fly","Female Anopheles mosquito","Tick"}'::text[], 2, 'Malaria is caused by Plasmodium parasites transmitted by female Anopheles mosquitoes. Houseflies spread other diseases like typhoid.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Health', 'Immunity', 'Vaccination works by:', '{"Killing all viruses in the body","Introducing weakened pathogens to build antibodies","Curing existing diseases","Replacing white blood cells"}'::text[], 1, 'Vaccination introduces weakened or dead pathogens to trigger the immune system to produce antibodies without causing the disease, providing immunity.', 'MCQ', 3, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Health', 'Hygiene', 'Which of the following is the most effective way to prevent the spread of cholera?', '{"Taking antibiotics weekly","Drinking only boiled or treated water","Avoiding all physical contact","Eating only fruits"}'::text[], 1, 'Cholera spreads mainly through contaminated water. Boiling or treating water kills the cholera bacteria. Antibiotics do not prevent infection.', 'MCQ', 2, true),

-- === Energy (4 questions) ===
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Energy', 'Forms', 'Which of the following is NOT a renewable source of energy?', '{"Solar energy","Wind energy","Natural gas","Hydroelectric power"}'::text[], 2, 'Natural gas is a fossil fuel (non-renewable). Solar, wind, and hydroelectric power are renewable because they naturally replenish.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'VERY_HARD', 'Energy', 'Energy Transfer', 'When a ball is thrown upward, what energy conversion takes place?', '{"Potential to kinetic","Kinetic to potential and then back to kinetic","Chemical to heat","Light to electrical"}'::text[], 1, 'When thrown upward, kinetic energy converts to potential energy at the peak, then back to kinetic energy as it falls back down.', 'MCQ', 3, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Energy', 'Electricity', 'A material that allows electric current to pass through it easily is called a:', '{"Insulator","Conductor","Transformer","Resistor"}'::text[], 1, 'Conductors (like copper, aluminum) allow electric current to flow easily. Insulators (like rubber, plastic) resist the flow of current.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Energy', 'Heat Transfer', 'The transfer of heat through a solid material without any movement of the material itself is called:', '{"Convection","Radiation","Conduction","Evaporation"}'::text[], 2, 'Conduction is heat transfer through direct contact in solids. Convection is in fluids, and radiation is through electromagnetic waves.', 'MCQ', 2, true),

-- === Forces (4 questions) ===
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Forces', 'Types', 'Which type of force opposes the motion of objects sliding past each other?', '{"Gravity","Magnetism","Friction","Tension"}'::text[], 2, 'Friction is a force that opposes motion between two surfaces in contact. Gravity pulls objects toward Earth, magnetism attracts magnetic materials.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Forces', 'Gravity', 'If you drop a stone and a feather from the same height in a vacuum (no air), which reaches the ground first?', '{"The stone","The feather","Both at the same time","Neither"}'::text[], 2, 'In a vacuum with no air resistance, all objects fall at the same rate regardless of mass, so both reach the ground simultaneously.', 'MCQ', 3, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Forces', 'Magnetism', 'Which of the following materials would be attracted to a magnet?', '{"Plastic ruler","Copper wire","Iron nail","Glass bottle"}'::text[], 2, 'Iron, nickel, and cobalt are magnetic materials. An iron nail would be attracted to a magnet. Plastic, copper, and glass are not magnetic.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'VERY_HARD', 'Forces', 'Simple Machines', 'A lever has its fulcrum between the load and the effort. Which class of lever is this?', '{"First-class lever","Second-class lever","Third-class lever","Not a lever"}'::text[], 0, 'In a first-class lever, the fulcrum is between the load and effort (e.g., seesaw, crowbar). Second-class has load in the middle, third-class has effort in the middle.', 'MCQ', 3, true),

-- === Air & Water (4 questions) ===
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Air', 'Properties', 'Which gas makes up the largest proportion of Earths atmosphere?', '{"Oxygen","Carbon dioxide","Nitrogen","Argon"}'::text[], 2, 'Nitrogen makes up about 78% of Earths atmosphere. Oxygen is about 21%, and other gases including carbon dioxide and argon make up the remaining 1%.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Air', 'Pressure', 'It is harder to breathe at high altitudes (like on a mountain) because:', '{"There is less oxygen in the air","The air pressure is lower, so each breath contains fewer oxygen molecules","The wind blows too hard","The air is too cold"}'::text[], 1, 'At high altitudes, air pressure is lower, meaning air molecules are more spread out. Each breath therefore contains fewer oxygen molecules.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Water', 'Properties', 'Water expands when it freezes. This means that ice is _____ than liquid water.', '{"Heavier","Less dense","More dense","Warmer"}'::text[], 1, 'Ice is less dense than liquid water, which is why ice floats. This unusual property occurs because water molecules form a crystalline structure when freezing.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'VERY_HARD', 'Water', 'Water Cycle', 'In the water cycle, the process by which water vapor turns back into liquid water droplets is called:', '{"Evaporation","Condensation","Precipitation","Transpiration"}'::text[], 1, 'Condensation is the change from water vapor (gas) to liquid water. Evaporation is liquid to gas, precipitation is water falling from clouds, transpiration is water loss from plants.', 'MCQ', 2, true),

-- === Light & Sound (4 questions) ===
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Light', 'Properties', 'Light travels in:', '{"Curved paths","Straight lines","Zigzag patterns","Circular patterns"}'::text[], 1, 'Light travels in straight lines. This is why shadows form and why we cant see around corners. This property is called rectilinear propagation.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Light', 'Reflection', 'When light bounces off a smooth surface like a mirror, this is called:', '{"Refraction","Reflection","Diffraction","Absorption"}'::text[], 1, 'Reflection is when light bounces off a surface. Refraction is when light bends as it passes from one medium to another (like from air to water).', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Sound', 'Properties', 'Sound travels fastest through:', '{"Air","Water","Steel","Vacuum"}'::text[], 2, 'Sound travels fastest through solids because molecules are packed closest together, allowing vibrations to transfer more quickly. Sound cannot travel through a vacuum.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Sound', 'Pitch', 'A high-pitched sound is produced when an object vibrates:', '{"Slowly","Quickly (at high frequency)","With large amplitude","Irregularly"}'::text[], 1, 'Pitch depends on frequency. High-frequency vibrations produce high-pitched sounds. Amplitude affects loudness, not pitch.', 'MCQ', 2, true),

-- === Environment (2 questions) ===
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Environment', 'Pollution', 'The excessive growth of algae in a pond due to fertilizers running off from farmland is called:', '{"Bioaccumulation","Eutrophication","Acid rain","Global warming"}'::text[], 1, 'Eutrophication occurs when excess nutrients (from fertilizers) enter water bodies, causing algal blooms that deplete oxygen and harm aquatic life.', 'MCQ', 3, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Environment', 'Conservation', 'Which practice best helps to conserve forests?', '{"Bush burning","Selective logging and reforestation","Cutting all trees in an area","Overgrazing"}'::text[], 1, 'Selective logging (cutting only mature trees) combined with reforestation (planting new trees) ensures forests can regenerate sustainably.', 'MCQ', 2, true),

-- === Weather & Climate (2 questions) ===
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Weather', 'Instruments', 'An instrument used to measure wind speed is called a:', '{"Barometer","Thermometer","Anemometer","Rain gauge"}'::text[], 2, 'An anemometer measures wind speed. A barometer measures air pressure, a thermometer measures temperature, and a rain gauge measures rainfall.', 'MCQ', 2, true),
('BASIC SCIENCE', 'PRIMARY', 'HARD', 'Weather', 'Climate', 'Nigeria experiences distinct wet and dry seasons primarily because of:', '{"Its distance from the equator","The movement of the Intertropical Convergence Zone (ITCZ)","Ocean currents","Mountain ranges"}'::text[], 1, 'The seasonal movement of the ITCZ causes the alternating wet and dry seasons in Nigeria. The ITCZ brings moist air during summer and dry air during winter.', 'MCQ', 3, true)

ON CONFLICT DO NOTHING;

-- ============================================================================
-- B) ISLAMIC STUDIES (25 questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Pillars of Islam', 'Shahadah', 'What is the first pillar of Islam?', '{"Salah","Shahadah (declaration of faith)","Zakah","Sawm"}'::text[], 1, 'Shahadah is the declaration of faith: "There is no god but Allah, and Muhammad is His Messenger." It is the foundation upon which all other pillars are built.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Pillars of Islam', 'Salah', 'How many obligatory (Fard) prayers must a Muslim perform each day?', '{"Three","Five","Seven","Ten"}'::text[], 1, 'Muslims are obligated to perform five daily prayers: Fajr, Dhuhr, Asr, Maghrib, and Isha.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Pillars of Islam', 'Zakah', 'Zakah is an obligatory charity calculated as what percentage of a Muslims savings?', '{"1%","2.5%","5%","10%"}'::text[], 1, 'Zakah is 2.5% of a Muslims qualifying savings held for one lunar year. It is one of the five pillars and purifies wealth.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Pillars of Islam', 'Sawm', 'During the month of Ramadan, Muslims fast from:', '{"Sunrise to sunset","Dawn (Fajr) until sunset (Maghrib)","Midnight to noon","Morning prayer to afternoon prayer"}'::text[], 1, 'Fasting during Ramadan begins at dawn (Fajr time) and ends at sunset (Maghrib time). Muslims abstain from food, drink, and other physical needs during this period.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Pillars of Islam', 'Hajj', 'The House of Allah (Kaaba) is located in which city?', '{"Medina","Jerusalem","Makkah","Cairo"}'::text[], 2, 'The Kaaba, the holiest site in Islam, is located in the Masjid al-Haram in Makkah, Saudi Arabia. It is the direction Muslims face during prayer (Qibla).', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'VERY_HARD', 'Pillars of Iman', 'Belief in Angels', 'Which angel is responsible for delivering revelations from Allah to the prophets?', '{"Angel Mika''il (Michael)","Angel Jibril (Gabriel)","Angel Israfeel (Raphael)","Angel Malakul-Mawt (Angel of Death)"}'::text[], 1, 'Angel Jibril (Gabriel) is the angel of revelation who delivered Allahs messages to all prophets, including the Quran to Prophet Muhammad (SAW).', 'MCQ', 3, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Pillars of Iman', 'Belief in Prophets', 'How many major prophets (Ulul Azm) are there in Islam, and who are they?', '{"Five: Nuh, Ibrahim, Musa, Isa, Muhammad","Three: Musa, Isa, Muhammad","Seven: including Adam, Idris, Hud","Ten: including all prophets mentioned in the Quran"}'::text[], 0, 'Ulul Azm are five major prophets who showed great patience and determination: Nuh (Noah), Ibrahim (Abraham), Musa (Moses), Isa (Jesus), and Muhammad (SAW).', 'MCQ', 3, true),
('ISLAMIC STUDIES', 'PRIMARY', 'VERY_HARD', 'Quran', 'Revelation', 'The Quran was revealed over a period of approximately how many years?', '{"10 years","13 years","23 years","30 years"}'::text[], 2, 'The Quran was revealed to Prophet Muhammad (SAW) over approximately 23 years, from 610 CE until his death in 632 CE.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Quran', 'Chapters', 'Which is the longest chapter (Surah) in the Quran?', '{"Surah Yaseen","Surah Al-Fatihah","Surah Al-Baqarah","Surah Al-Ikhlas"}'::text[], 2, 'Surah Al-Baqarah (The Cow) is the longest chapter in the Quran with 286 verses. Surah Al-Ikhlas is one of the shortest.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Quran', 'Content', 'Surah Al-Fatihah is also known as:', '{"The Throne Verse","The Opening","The Chapter of Sincerity","The Light"}'::text[], 1, 'Surah Al-Fatihah is called "The Opening" (Al-Fatihah) because it opens the Quran. It is also known as Ummul-Kitab (Mother of the Book) and consists of 7 verses.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Hadith', 'Definition', 'What is a Hadith?', '{"A verse from the Quran","A saying, action, or approval of Prophet Muhammad","A type of prayer","An Islamic festival"}'::text[], 1, 'Hadith refers to the sayings, actions, and approvals of Prophet Muhammad (SAW). Together with the Quran, they form the primary sources of Islamic law.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'VERY_HARD', 'Hadith', 'Authenticity', 'A hadith with a continuous chain of reliable narrators up to the Prophet is called:', '{"Hadith Qudsi","Hadith Sahih (authentic)","Hadith Da''if (weak)","Hadith Hasan (good)"}'::text[], 1, 'A Sahih hadith has an unbroken chain of reliable narrators, is free from irregularities, and is considered authentic and a valid source of Islamic law.', 'MCQ', 3, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Islamic Ethics', 'Honesty', 'The Prophet Muhammad (SAW) was known by which title even before his prophethood, meaning "the trustworthy"?', '{"Al-Mustafa","Al-Amin","Ar-Rahim","Al-Karim"}'::text[], 1, 'Prophet Muhammad was known as "Al-Amin" (the trustworthy) among his people even before he received prophethood, because of his honesty and integrity.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'VERY_HARD', 'Islamic Ethics', 'Treatment of Parents', 'In the Quran, Allah mentions that a person should treat parents with kindness. What specific reason is given for this?', '{"Because they are wealthy","Because they carried and cared for us with hardship","Because they are older","Because they know more"}'::text[], 1, 'The Quran specifically mentions that parents carried us through pregnancy and hardship, raised us with love, and sacrificed for us, so we must treat them with utmost respect and care.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Islamic Ethics', 'Charity', 'A charitable act that continues to benefit others even after a person has died is called:', '{"Sadaqah","Sadaqah Jariyah (ongoing charity)","Zakah","Fidyah"}'::text[], 1, 'Sadaqah Jariyah is ongoing charity that continues to benefit people, such as building a well, planting a tree, or teaching beneficial knowledge.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Islamic History', 'Migration', 'The migration of Prophet Muhammad and his companions from Makkah to Medina is known as:', '{"Fajr","Hijrah","Jihad","Dawah"}'::text[], 1, 'The Hijrah (migration) from Makkah to Medina in 622 CE marks the beginning of the Islamic calendar. It was undertaken to escape persecution and establish the first Muslim community.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Islamic History', 'Companions', 'Who was the first person to accept Islam?', '{"Umar ibn al-Khattab","Khadijah bint Khuwaylid","Abu Bakr as-Siddiq","Ali ibn Abi Talib"}'::text[], 1, 'Khadijah, the wife of Prophet Muhammad (SAW), was the first person to accept Islam after receiving the first revelation.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Islamic History', 'Battles', 'In the Battle of Badr, how many Muslims fought against the Quraysh army?', '{"About 100","About 313","About 500","About 1000"}'::text[], 1, 'Approximately 313 Muslims faced over 1,000 Quraysh soldiers at Badr. Despite being outnumbered, the Muslims achieved a decisive victory through divine assistance.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'VERY_HARD', 'Acts of Worship', 'Wudu', 'When performing Wudu (ablution), which of the following actions is Fard (obligatory)?', '{"Rinsing the mouth","Washing the face","Sniffing water into the nose","Wiping the ears"}'::text[], 1, 'Washing the face is one of the obligatory (Fard) acts of Wudu. Rinsing the mouth, sniffing water into the nose, and wiping ears are Sunnah.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'VERY_HARD', 'Acts of Worship', 'Salah', 'What is the first thing a person will be asked about on the Day of Judgment according to hadith?', '{"Their wealth","Their Salah (prayer)","Their family","Their knowledge"}'::text[], 1, 'According to a hadith, the first deed a person will be questioned about on the Day of Judgment is their Salah. If it is accepted, other deeds will be accepted.', 'MCQ', 3, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Acts of Worship', 'Sawm', 'Which of the following breaks a fast during Ramadan?', '{"Using a miswak","Tasting food without swallowing","Swallowing water while performing Ghusl","Deliberately vomiting"}'::text[], 3, 'Deliberately vomiting breaks the fast. Using miswak, tasting without swallowing, and accidental water during Ghusl do not break the fast.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'VERY_HARD', 'Islamic History', 'Caliphs', 'The rightly guided caliphs (Khulafaur Rashidun) ruled after Prophet Muhammad. Who was the fourth caliph?', '{"Umar ibn al-Khattab","Uthman ibn Affan","Ali ibn Abi Talib","Abu Bakr as-Siddiq"}'::text[], 2, 'The Khulafaur Rashidun in order: Abu Bakr (1st), Umar (2nd), Uthman (3rd), and Ali (4th). Their collective rule lasted about 30 years after the Prophet.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Acts of Worship', 'Dua', 'In which language can a Muslim make Dua (supplication) to Allah?', '{"Only Arabic","Only the persons native language","Any language","Only during Hajj"}'::text[], 2, 'Dua (supplication) can be made in any language because Allah understands all languages. It is a personal conversation between a servant and their Creator.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Quran', 'Memorization', 'Someone who has memorized the entire Quran is called a:', '{"Qari","Hafiz","Imam","Mufti"}'::text[], 1, 'A Hafiz (male) or Hafiza (female) is someone who has memorized the entire Quran. A Qari is a skilled reciter, an Imam leads prayer, and a Mufti issues religious rulings.', 'MCQ', 2, true),
('ISLAMIC STUDIES', 'PRIMARY', 'HARD', 'Islamic Ethics', 'Neighbors', 'According to hadith, how far does the right of a neighbor extend?', '{"Next door only","Up to 40 houses in all directions","Same street only","Same compound only"}'::text[], 1, 'According to hadith, the rights of neighbors extend to 40 houses in all directions. This shows the importance Islam places on maintaining good neighborly relations.', 'MCQ', 3, true)

ON CONFLICT DO NOTHING;

-- ============================================================================
-- C) GENERAL KNOWLEDGE (25 questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Nigerian History', 'Independence', 'Nigeria gained independence from Britain on which date?', '{"September 15, 1960","October 1, 1960","October 1, 1963","January 15, 1966"}'::text[], 1, 'Nigeria gained independence from British colonial rule on October 1, 1960. Nigeria became a republic on October 1, 1963.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Nigerian History', 'Heroes', 'Who was the first Prime Minister of Nigeria?', '{"Nnamdi Azikiwe","Obafemi Awolowo","Abubakar Tafawa Balewa","Ahmadu Bello"}'::text[], 2, 'Sir Abubakar Tafawa Balewa served as Nigerias first and only Prime Minister from 1960 to 1966. Nnamdi Azikiwe was the first President (ceremonial).', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'VERY_HARD', 'Nigerian History', 'Civil War', 'The Nigerian Civil War (Biafran War) lasted from:', '{"1960 to 1963","1966 to 1970","1967 to 1970","1970 to 1975"}'::text[], 2, 'The Nigerian Civil War lasted from July 6, 1967 to January 15, 1970. It was fought between Nigeria and the secessionist state of Biafra.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Nigerian History', 'Constitution', 'What year did Nigeria become a Federal Republic?', '{"1960","1961","1963","1979"}'::text[], 2, 'Nigeria became a Federal Republic on October 1, 1963, with Nnamdi Azikiwe as the first President.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Geography', 'States', 'How many states does Nigeria currently have?', '{"12 states","36 states","30 states","37 states"}'::text[], 1, 'Nigeria has 36 states and the Federal Capital Territory (Abuja). The states were created through several state creation exercises since independence.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Geography', 'Rivers', 'Which is the longest river in Nigeria?', '{"River Benue","River Niger","River Kaduna","River Sokoto"}'::text[], 1, 'River Niger is the longest river in Nigeria, stretching about 4,180 km. River Benue is the longest tributary.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'VERY_HARD', 'Geography', 'Landmarks', 'Aso Rock, a prominent landmark in Nigeria, is located in:', '{"Lagos","Kano","Abuja","Calabar"}'::text[], 2, 'Aso Rock is a 400-meter monolith located in Abuja, the capital of Nigeria. The Presidential Villa, National Assembly, and Supreme Court are located around it.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Geography', 'Continents', 'Which is the largest continent by land area?', '{"Africa","North America","Asia","Europe"}'::text[], 2, 'Asia is the largest continent by land area, covering about 44.58 million square kilometers (30% of Earths land area). Africa is the second largest.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Geography', 'Oceans', 'Which is the deepest ocean in the world?', '{"Atlantic Ocean","Indian Ocean","Pacific Ocean","Arctic Ocean"}'::text[], 2, 'The Pacific Ocean is the largest and deepest ocean. Its deepest point, the Mariana Trench, reaches about 11,034 meters below sea level.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Civics', 'Government', 'The three arms of government in Nigeria are:', '{"Federal, State, Local","Executive, Legislature, Judiciary","Army, Navy, Air Force","Central, State, Municipal"}'::text[], 1, 'The three arms of government are the Executive (implements laws), Legislature (makes laws), and Judiciary (interprets laws). This separation ensures checks and balances.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Civics', 'Rights', 'The right to vote in Nigeria is granted to citizens who have attained the age of:', '{"16 years","18 years","21 years","25 years"}'::text[], 1, 'Nigerian citizens who are 18 years and above and are registered to vote are eligible to participate in elections.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'VERY_HARD', 'Civics', 'Symbols', 'What do the two green bands on the Nigerian flag represent?', '{"Peace and unity","Agricultural wealth and natural resources","Hope and faith","The northern and southern regions"}'::text[], 1, 'The two green bands on the Nigerian flag represent agricultural wealth and natural resources. The white band represents peace and unity.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Current Affairs', 'Organizations', 'Nigeria is a member of which of the following international organizations?', '{"Only the United Nations","UN, African Union, OPEC, and ECOWAS","Only ECOWAS","Only OPEC"}'::text[], 1, 'Nigeria is a member of multiple international organizations including the United Nations (UN), African Union (AU), OPEC, ECOWAS, and the Commonwealth.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Current Affairs', 'Climate', 'The annual climate conference where world leaders discuss climate change is called:', '{"G7 Summit","COP (Conference of the Parties)","World Economic Forum","UN General Assembly"}'::text[], 1, 'COP (Conference of the Parties) is the annual United Nations climate change conference where nations negotiate climate action targets and policies.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'VERY_HARD', 'Famous People', 'Scientists', 'Albert Einstein is famous for developing the theory of:', '{"Gravity","Evolution","Relativity","Electricity"}'::text[], 2, 'Albert Einstein developed the theory of relativity (E=mc²). Newton developed the theory of gravity, Darwin the theory of evolution.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Famous People', 'Leaders', 'Nelson Mandela, a famous anti-apartheid leader, was from which country?', '{"Nigeria","Ghana","South Africa","Kenya"}'::text[], 2, 'Nelson Mandela was from South Africa. He spent 27 years in prison and became the first black President of South Africa in 1994.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Science', 'Inventions', 'The telephone was invented by:', '{"Thomas Edison","Alexander Graham Bell","Nikola Tesla","Albert Einstein"}'::text[], 1, 'Alexander Graham Bell is credited with inventing the first practical telephone in 1876. Thomas Edison invented the light bulb.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Science', 'Space', 'The first human to walk on the moon was:', '{"Yuri Gagarin","Neil Armstrong","Buzz Aldrin","John Glenn"}'::text[], 1, 'Neil Armstrong was the first person to walk on the moon on July 20, 1969, as part of the Apollo 11 mission. His famous words: "Thats one small step for man..."', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'World Knowledge', 'Countries', 'Which country has the largest population in the world as of recent years?', '{"China","India","United States","Indonesia"}'::text[], 1, 'India surpassed China to become the most populous country in the world in 2023, with over 1.4 billion people.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'World Knowledge', 'Landmarks', 'The tallest building in the world, standing at 828 meters, is called:', '{"Shanghai Tower","Burj Khalifa","Abraj Al-Bait Clock Tower","One World Trade Center"}'::text[], 1, 'Burj Khalifa in Dubai, UAE, is the worlds tallest building at 828 meters (2,717 feet). It has 163 floors.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Nigerian History', 'Leaders', 'Who was the first Executive President of Nigeria?', '{"Nnamdi Azikiwe","Shehu Shagari","Olusegun Obasanjo","Murtala Mohammed"}'::text[], 1, 'Shehu Shagari became Nigerias first Executive President in 1979 under the Second Republic. (Azikiwe was a ceremonial President, not Executive.)', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'VERY_HARD', 'Geography', 'Population', 'Which is the most populous city in Africa?', '{"Cairo, Egypt","Lagos, Nigeria","Kinshasa, DRC","Johannesburg, South Africa"}'::text[], 1, 'Lagos, Nigeria is the most populous city in Africa with over 15 million people in its metropolitan area. Cairo is the second most populous.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Civics', 'Taxation', 'The money that citizens and businesses pay to the government to fund public services is called:', '{"Fines","Taxes","Donations","Fees"}'::text[], 1, 'Taxes are mandatory payments to government used to fund public services like roads, schools, hospitals, and security.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'World Knowledge', 'Sports', 'The Olympic Games originated in which ancient country?', '{"Egypt","Rome","Greece","Persia"}'::text[], 2, 'The ancient Olympic Games began in Olympia, Greece around 776 BC. The modern Olympic Games were revived in 1896.', 'MCQ', 2, true),
('GENERAL KNOWLEDGE', 'PRIMARY', 'HARD', 'Current Affairs', 'Technology', 'The global network that connects computers worldwide and allows information sharing is called:', '{"The Internet","The World Wide Web only","Social media","A local network"}'::text[], 0, 'The Internet is the global network infrastructure that connects computers worldwide. The World Wide Web (WWW) is a service that runs on the Internet.', 'MCQ', 2, true)

ON CONFLICT DO NOTHING;
