-- ============================================================================
-- SEED ADDITIONAL SUBJECTS: Fill gaps across all levels
-- ============================================================================
-- Adds challenging questions for subjects that currently have zero coverage:
--   JSS: BASIC SCIENCE, BUSINESS STUDIES, PRE-VOCATIONAL STUDIES
--   SS:  PHYSICS, CHEMISTRY, BIOLOGY, GEOGRAPHY
--   PRIMARY: VERBAL REASONING, QUANTITATIVE REASONING, extra MATHEMATICS & ENGLISH
-- SAFE TO RE-RUN: Uses ON CONFLICT DO NOTHING
-- ============================================================================

-- ============================================================================
-- JSS 1-3: BASIC SCIENCE (25 questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
-- JSS1 (8 questions)
('BASIC SCIENCE', 'JSS1', 'HARD', 'Living Things', 'Classification', 'Which of the following is NOT a characteristic of living things?', '{"Growth","Movement","Photosynthesis","Reproduction"}'::text[], 2, 'Photosynthesis is a process carried out by plants, not a characteristic of all living things. The basic characteristics are movement, respiration, growth, reproduction, etc.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS1', 'HARD', 'Living Things', 'Cells', 'The basic unit of structure and function in all living organisms is the:', '{"Tissue","Organ","Cell","Nucleus"}'::text[], 2, 'The cell is the fundamental unit of life. Tissues are groups of cells, organs are groups of tissues.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS1', 'HARD', 'Living Things', 'Sense Organs', 'The part of the eye that controls the amount of light entering is the:', '{"Retina","Pupil","Iris","Lens"}'::text[], 2, 'The iris controls the size of the pupil, which regulates the amount of light entering the eye.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS1', 'VERY_HARD', 'Health', 'Diseases', 'Which vitamin deficiency causes rickets in children?', '{"Vitamin A","Vitamin C","Vitamin D","Vitamin B12"}'::text[], 2, 'Rickets is caused by Vitamin D deficiency, leading to softening and weakening of bones.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS1', 'HARD', 'Environment', 'Pollution', 'The type of pollution caused by excessive noise from generators and loudspeakers is called:', '{"Air pollution","Water pollution","Noise pollution","Land pollution"}'::text[], 2, 'Noise pollution is unwanted or excessive sound that can harm human health and the environment.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS1', 'HARD', 'Living Things', 'Reproduction', 'The male reproductive cell in flowering plants is called:', '{"Ovule","Pollen grain","Style","Anther"}'::text[], 1, 'Pollen grains contain the male gametes in flowering plants. Ovules contain the female gametes.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS1', 'HARD', 'Matter', 'States', 'The change of state from solid directly to gas is called:', '{"Melting","Evaporation","Sublimation","Condensation"}'::text[], 2, 'Sublimation is the direct change from solid to gas (e.g., dry ice, camphor).', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS1', 'VERY_HARD', 'Energy', 'Forms', 'The energy possessed by a moving car is an example of:', '{"Potential energy","Chemical energy","Kinetic energy","Nuclear energy"}'::text[], 2, 'Kinetic energy is the energy of motion. A moving car has kinetic energy.', 'MCQ', 2, true),

-- JSS2 (9 questions)
('BASIC SCIENCE', 'JSS2', 'HARD', 'Human Body', 'Digestive System', 'The enzyme in the mouth that begins the digestion of starch is called:', '{"Pepsin","Amylase","Lipase","Trypsin"}'::text[], 1, 'Salivary amylase (ptyalin) begins the digestion of starch into maltose in the mouth.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS2', 'HARD', 'Human Body', 'Circulatory System', 'The largest artery in the human body is the:', '{"Pulmonary artery","Aorta","Carotid artery","Femoral artery"}'::text[], 1, 'The aorta is the largest artery, carrying oxygenated blood from the left ventricle to the rest of the body.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS2', 'HARD', 'Human Body', 'Respiratory System', 'During inhalation, the diaphragm:', '{"Relaxes and moves up","Contracts and flattens","Stays still","Moves sideways"}'::text[], 1, 'During inhalation, the diaphragm contracts and flattens, increasing chest volume and drawing air into the lungs.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS2', 'VERY_HARD', 'Living Things', 'Ecology', 'An organism that hunts and eats other organisms is called a:', '{"Prey","Predator","Scavenger","Decomposer"}'::text[], 1, 'A predator is an organism that hunts and kills other organisms (prey) for food.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS2', 'HARD', 'Matter', 'Atoms', 'The smallest particle of an element that can take part in a chemical reaction is:', '{"Molecule","Atom","Electron","Proton"}'::text[], 1, 'An atom is the smallest particle of an element that retains its chemical properties.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS2', 'HARD', 'Forces', 'Friction', 'Friction can be reduced by using:', '{"Sandpaper","Rough surfaces","Lubricants","Heavy weights"}'::text[], 2, 'Lubricants like oil and grease reduce friction by creating a slippery layer between surfaces.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS2', 'HARD', 'Energy', 'Sources', 'Which of these is a non-renewable energy source?', '{"Solar","Wind","Natural gas","Hydroelectric"}'::text[], 2, 'Natural gas is a fossil fuel formed over millions of years and is non-renewable. Solar, wind, and hydro are renewable.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS2', 'VERY_HARD', 'Human Body', 'Excretory System', 'The organ that filters waste products from the blood to produce urine is the:', '{"Liver","Lungs","Kidney","Skin"}'::text[], 2, 'The kidneys filter waste products like urea from the blood and produce urine. The liver detoxifies chemicals.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS2', 'HARD', 'Environment', 'Conservation', 'Bush burning is harmful because it:', '{"Kills soil microorganisms and destroys habitats","Increases soil fertility","Causes rainfall","Creates more farmland"}'::text[], 0, 'Bush burning kills soil organisms, destroys habitats, releases carbon dioxide, and can lead to soil erosion.', 'MCQ', 2, true),

-- JSS3 (8 questions)
('BASIC SCIENCE', 'JSS3', 'HARD', 'Chemistry', 'Elements', 'The horizontal rows in the Periodic Table are called:', '{"Groups","Periods","Families","Blocks"}'::text[], 1, 'Rows in the Periodic Table are called periods. Vertical columns are called groups or families.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS3', 'HARD', 'Human Body', 'Nervous System', 'The three main parts of the brain are the:', '{"Cerebrum, cerebellum, medulla oblongata","Frontal, parietal, temporal","Neurons, axons, dendrites","Gray matter, white matter, spinal cord"}'::text[], 0, 'The three main parts are the cerebrum (thinking), cerebellum (coordination), and medulla oblongata (automatic functions).', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS3', 'VERY_HARD', 'Chemistry', 'Reactions', 'The reaction between an acid and a base to form salt and water is called:', '{"Oxidation","Reduction","Neutralization","Hydrolysis"}'::text[], 2, 'Neutralization is the reaction between an acid and a base producing salt and water.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS3', 'HARD', 'Energy', 'Electricity', 'The unit of electric current is:', '{"Volt","Ampere","Ohm","Watt"}'::text[], 1, 'Electric current is measured in amperes (amps). Voltage is in volts, resistance in ohms, power in watts.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS3', 'HARD', 'Living Things', 'Genetics', 'The thread-like structures in the nucleus that carry genetic information are:', '{"Chromosomes","Ribosomes","Mitochondria","Lysosomes"}'::text[], 0, 'Chromosomes carry DNA and genetic information. Ribosomes make proteins, mitochondria produce energy.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS3', 'HARD', 'Human Body', 'Endocrine System', 'The master gland that controls other endocrine glands is the:', '{"Thyroid gland","Pituitary gland","Adrenal gland","Pancreas"}'::text[], 1, 'The pituitary gland in the brain controls many other endocrine glands and is called the master gland.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS3', 'VERY_HARD', 'Light', 'Optics', 'The splitting of white light into its component colors is called:', '{"Reflection","Refraction","Diffraction","Dispersion"}'::text[], 3, 'Dispersion is the splitting of white light into its constituent colors (ROYGBIV) through a prism.', 'MCQ', 2, true),
('BASIC SCIENCE', 'JSS3', 'HARD', 'Environment', 'Ecosystem', 'The process by which green plants make their own food using sunlight is:', '{"Transpiration","Photosynthesis","Respiration","Fermentation"}'::text[], 1, 'Photosynthesis uses sunlight, carbon dioxide, and water to produce glucose and oxygen.', 'MCQ', 2, true)

ON CONFLICT DO NOTHING;

-- ============================================================================
-- JSS 1-3: BUSINESS STUDIES (15 questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
('BUSINESS STUDIES', 'JSS1', 'HARD', 'Office Equipment', 'Types', 'A computer is an example of what type of office equipment?', '{"Furniture","Stationery","Electronic equipment","Consumables"}'::text[], 2, 'Computers are electronic office equipment used for data processing, storage, and communication.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS1', 'HARD', 'Commerce', 'Trade', 'The buying and selling of goods and services is called:', '{"Production","Consumption","Trade","Manufacturing"}'::text[], 2, 'Trade is the exchange of goods and services between buyers and sellers for mutual benefit.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS1', 'HARD', 'Office Procedure', 'Correspondence', 'A letter written within an organization is called:', '{"Business letter","Memorandum","Invoice","Receipt"}'::text[], 1, 'A memorandum (memo) is used for internal communication within an organization.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS1', 'VERY_HARD', 'Commerce', 'Banking', 'The type of account that allows unlimited withdrawals and earns little or no interest is:', '{"Fixed deposit account","Savings account","Current account","Joint account"}'::text[], 2, 'A current account allows unlimited withdrawals (often by cheque) but earns little or no interest.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS2', 'HARD', 'Commerce', 'Transport', 'Which mode of transport is most suitable for transporting crude oil over long distances?', '{"Road","Rail","Pipeline","Air"}'::text[], 2, 'Pipelines are the most efficient and cost-effective way to transport crude oil and petroleum products over land.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS2', 'HARD', 'Commerce', 'Advertising', 'The main purpose of advertising is to:', '{"Entertain consumers","Promote and sell products","Reduce prices","Educate the public"}'::text[], 1, 'The primary purpose of advertising is to promote products and services to potential customers to increase sales.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS2', 'HARD', 'Office Procedure', 'Filing', 'The method of arranging files in alphabetical order is called:', '{"Chronological filing","Alphabetical filing","Numerical filing","Subject filing"}'::text[], 1, 'Alphabetical filing arranges documents in A-Z order by name or title.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS2', 'VERY_HARD', 'Commerce', 'Insurance', 'The principle of insurance that prevents a person from profiting from an insured loss is:', '{"Utmost good faith","Subrogation","Indemnity","Insurable interest"}'::text[], 2, 'Indemnity ensures that the insured is restored to their original financial position, not enriched by a loss.', 'MCQ', 3, true),
('BUSINESS STUDIES', 'JSS2', 'HARD', 'Commerce', 'Communication', 'Which of these is a form of oral communication?', '{"Email","Telephone call","Memo","Report"}'::text[], 1, 'A telephone call is oral (spoken) communication. Email, memos, and reports are written communication.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS3', 'HARD', 'Commerce', 'Trade', 'The Middlemen in the chain of distribution include:', '{"Manufacturers and consumers","Wholesalers and retailers","Farmers and miners","Bankers and insurers"}'::text[], 1, 'Wholesalers and retailers are middlemen who buy from producers and sell to consumers.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS3', 'HARD', 'Commerce', 'E-Commerce', 'Buying and selling of goods over the internet is called:', '{"E-Banking","E-Commerce","E-Government","E-Learning"}'::text[], 1, 'E-commerce (electronic commerce) involves buying and selling goods and services online.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS3', 'HARD', 'Entrepreneurship', 'Business Plan', 'A document that outlines the goals, strategies, and financial forecasts of a business is called a:', '{"Balance sheet","Business plan","Invoice","Receipt"}'::text[], 1, 'A business plan describes the business goals, strategies, market analysis, and financial projections.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS3', 'VERY_HARD', 'Commerce', 'Taxation', 'Value Added Tax (VAT) in Nigeria is currently charged at what rate?', '{"5%","7.5%","10%","15%"}'::text[], 1, 'VAT in Nigeria is currently 7.5% on most goods and services, introduced as an increase from 5% in 2020.', 'MCQ', 3, true),
('BUSINESS STUDIES', 'JSS3', 'HARD', 'Commerce', 'International Trade', 'The difference between a countrys exports and imports is called:', '{"Balance of trade","National income","Gross domestic product","Inflation rate"}'::text[], 0, 'Balance of trade (trade balance) is the difference between the value of exports and imports.', 'MCQ', 2, true),
('BUSINESS STUDIES', 'JSS3', 'HARD', 'Office Procedure', 'Meetings', 'The official written record of what happened during a meeting is called:', '{"Agenda","Minutes","Report","Notice"}'::text[], 1, 'Minutes are the official written record of discussions, decisions, and resolutions made during a meeting.', 'MCQ', 2, true)

ON CONFLICT DO NOTHING;

-- ============================================================================
-- JSS 1-3: PRE-VOCATIONAL STUDIES (12 questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
('PRE-VOCATIONAL STUDIES', 'JSS1', 'HARD', 'Agriculture', 'Farming', 'The practice of rearing fish in enclosed ponds is called:', '{"Fishery","Pisciculture","Aquaculture","Fish farming"}'::text[], 2, 'Aquaculture is the farming of fish and other aquatic organisms. Pisciculture specifically refers to fish rearing.', 'MCQ', 2, true),
('PRE-VOCATIONAL STUDIES', 'JSS1', 'HARD', 'Home Economics', 'Nutrition', 'A balanced diet contains all the following EXCEPT:', '{"Carbohydrates","Proteins","Artificial preservatives","Vitamins"}'::text[], 2, 'A balanced diet includes carbohydrates, proteins, fats, vitamins, minerals, and water. Artificial preservatives are not nutrients.', 'MCQ', 2, true),
('PRE-VOCATIONAL STUDIES', 'JSS1', 'HARD', 'Agriculture', 'Crops', 'Cassava, yam, and cocoyam are examples of:', '{"Cereal crops","Root and tuber crops","Leguminous crops","Oil crops"}'::text[], 1, 'Cassava, yam, and cocoyam are root and tuber crops grown primarily for their edible underground parts.', 'MCQ', 2, true),
('PRE-VOCATIONAL STUDIES', 'JSS1', 'VERY_HARD', 'Home Economics', 'Sewing', 'The temporary stitch used to hold two pieces of fabric together before permanent sewing is called:', '{"Running stitch","Back stitch","Tacking/basting stitch","Hemming stitch"}'::text[], 2, 'Tacking or basting stitch is a temporary stitch used to hold fabric pieces in place before final sewing.', 'MCQ', 2, true),
('PRE-VOCATIONAL STUDIES', 'JSS2', 'HARD', 'Agriculture', 'Animal Husbandry', 'The process by which farm animals convert feed into body tissues and products is called:', '{"Digestion","Metabolism","Assimilation","Nutrition"}'::text[], 2, 'Assimilation is the process by which absorbed nutrients are used by the body for growth and tissue repair.', 'MCQ', 2, true),
('PRE-VOCATIONAL STUDIES', 'JSS2', 'HARD', 'Home Economics', 'Food Preservation', 'The method of preserving food by removing water content is called:', '{"Pasteurization","Dehydration","Refrigeration","Canning"}'::text[], 1, 'Dehydration removes water from food, preventing microorganism growth. Examples include dried fish and garri.', 'MCQ', 2, true),
('PRE-VOCATIONAL STUDIES', 'JSS2', 'HARD', 'Agriculture', 'Farm Tools', 'A tool used for cutting grasses and weeds is called a:', '{"Hoe","Cutlass/machete","Spade","Rake"}'::text[], 1, 'A cutlass or machete is used for cutting grass, weeds, and clearing farmlands.', 'MCQ', 2, true),
('PRE-VOCATIONAL STUDIES', 'JSS2', 'VERY_HARD', 'Home Economics', 'First Aid', 'The first step in treating a minor burn is to:', '{"Apply butter","Cool the burn under running water","Puncture any blisters","Apply toothpaste"}'::text[], 1, 'Cooling a burn under running water for at least 10 minutes reduces tissue damage and pain.', 'MCQ', 2, true),
('PRE-VOCATIONAL STUDIES', 'JSS3', 'HARD', 'Agriculture', 'Farm Management', 'The record that shows the daily activities on a farm is called:', '{"Inventory record","Farm diary","Profit and loss account","Balance sheet"}'::text[], 1, 'A farm diary records daily farm activities including planting, harvesting, and weather observations.', 'MCQ', 2, true),
('PRE-VOCATIONAL STUDIES', 'JSS3', 'HARD', 'Home Economics', 'Housing', 'Natural ventilation in a house is achieved through:', '{"Air conditioners","Windows and ventilators","Fans","Dehumidifiers"}'::text[], 1, 'Natural ventilation uses windows, doors, and ventilators to allow air to flow through a building.', 'MCQ', 2, true),
('PRE-VOCATIONAL STUDIES', 'JSS3', 'HARD', 'Agriculture', 'Pest Control', 'Using natural enemies to control agricultural pests is called:', '{"Chemical control","Biological control","Mechanical control","Cultural control"}'::text[], 1, 'Biological control uses natural predators, parasites, or pathogens to control pest populations.', 'MCQ', 2, true),
('PRE-VOCATIONAL STUDIES', 'JSS3', 'HARD', 'Home Economics', 'Budgeting', 'A plan showing expected income and expenditure over a period is called a:', '{"Budget","Receipt","Invoice","Ledger"}'::text[], 0, 'A budget is a financial plan that estimates income and expenses for a specific period.', 'MCQ', 2, true)

ON CONFLICT DO NOTHING;

-- ============================================================================
-- SS1-SS2: PHYSICS (20 questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
('PHYSICS', 'SS1', 'HARD', 'Motion', 'Speed and Velocity', 'A car travels 120 kilometers in 2 hours. What is its average speed?', '{"40 km/h","60 km/h","80 km/h","240 km/h"}'::text[], 1, 'Speed = distance / time = 120 km / 2 h = 60 km/h.', 'MCQ', 2, true),
('PHYSICS', 'SS1', 'HARD', 'Motion', 'Acceleration', 'If a vehicle increases its speed from 10 m/s to 30 m/s in 5 seconds, its acceleration is:', '{"2 m/s²","4 m/s²","6 m/s²","8 m/s²"}'::text[], 1, 'Acceleration = (final velocity - initial velocity) / time = (30 - 10) / 5 = 4 m/s².', 'MCQ', 2, true),
('PHYSICS', 'SS1', 'VERY_HARD', 'Motion', 'Newton''s Laws', 'According to Newton''s First Law, an object in motion will continue in motion unless acted upon by:', '{"Gravity only","An unbalanced external force","Friction only","Air resistance"}'::text[], 1, 'Newton''s First Law (Law of Inertia): an object remains at rest or in uniform motion unless acted on by an unbalanced external force.', 'MCQ', 2, true),
('PHYSICS', 'SS1', 'HARD', 'Energy', 'Work and Power', 'Work is done when a force of 50 N moves an object through 4 meters. Calculate the work done.', '{"54 J","100 J","200 J","400 J"}'::text[], 2, 'Work = force × distance = 50 N × 4 m = 200 Joules.', 'MCQ', 2, true),
('PHYSICS', 'SS1', 'VERY_HARD', 'Energy', 'Kinetic and Potential', 'A stone of mass 2 kg is dropped from a height of 10 m. What is its kinetic energy just before hitting the ground? (g = 10 m/s²)', '{"20 J","100 J","200 J","400 J"}'::text[], 2, 'Using conservation of energy: KE = PE = mgh = 2 × 10 × 10 = 200 J.', 'MCQ', 3, true),
('PHYSICS', 'SS1', 'HARD', 'Light', 'Reflection', 'The angle of incidence is equal to:', '{"The angle of refraction","The angle of reflection","90° minus the angle","The critical angle"}'::text[], 1, 'The law of reflection states that the angle of incidence equals the angle of reflection.', 'MCQ', 2, true),
('PHYSICS', 'SS1', 'HARD', 'Sound', 'Characteristics', 'The loudness of a sound depends on the:', '{"Frequency","Amplitude","Wavelength","Speed"}'::text[], 1, 'Loudness is determined by the amplitude of the sound wave. Higher amplitude = louder sound.', 'MCQ', 2, true),
('PHYSICS', 'SS1', 'HARD', 'Electricity', 'Current', 'The relationship between voltage (V), current (I), and resistance (R) is given by:', '{"Ohm''s Law: V = IR","Faraday''s Law","Coulomb''s Law","Newton''s Law"}'::text[], 0, 'Ohm''s Law states that voltage across a conductor equals current times resistance (V = IR).', 'MCQ', 2, true),
('PHYSICS', 'SS2', 'HARD', 'Waves', 'Properties', 'The number of complete waves passing a point per second is the:', '{"Wavelength","Frequency","Amplitude","Period"}'::text[], 1, 'Frequency is the number of complete waves passing a point per second, measured in Hertz (Hz).', 'MCQ', 2, true),
('PHYSICS', 'SS2', 'VERY_HARD', 'Electricity', 'Circuits', 'Three resistors of 2Ω, 3Ω, and 5Ω are connected in series. The total resistance is:', '{"1.2Ω","3.3Ω","6.5Ω","10Ω"}'::text[], 3, 'In series connection, total resistance = 2 + 3 + 5 = 10Ω.', 'MCQ', 2, true),
('PHYSICS', 'SS2', 'HARD', 'Heat', 'Temperature', 'The temperature scale that has absolute zero as its starting point is:', '{"Celsius","Fahrenheit","Kelvin","Reaumur"}'::text[], 2, 'The Kelvin (absolute) scale starts at absolute zero (-273°C), where molecular motion theoretically stops.', 'MCQ', 2, true),
('PHYSICS', 'SS2', 'HARD', 'Electricity', 'Electromagnetism', 'A device that converts electrical energy to mechanical energy is called:', '{"Generator","Transformer","Electric motor","Dynamo"}'::text[], 2, 'An electric motor converts electrical energy to mechanical energy. A generator does the opposite.', 'MCQ', 2, true),
('PHYSICS', 'SS2', 'VERY_HARD', 'Light', 'Refraction', 'When light passes from air to water, it bends:', '{"Away from the normal","Towards the normal","Does not bend","Parallel to the surface"}'::text[], 1, 'Light bends towards the normal when moving from a less dense (air) to a denser medium (water).', 'MCQ', 2, true),
('PHYSICS', 'SS2', 'HARD', 'Sound', 'Speed', 'The speed of sound in air at room temperature is approximately:', '{"340 m/s","1500 m/s","300,000 km/s","3 × 10³ m/s"}'::text[], 0, 'Sound travels at approximately 340 m/s in air. Light travels at 300,000 km/s.', 'MCQ', 2, true),
('PHYSICS', 'SS2', 'HARD', 'Energy', 'Heat Transfer', 'The method of heat transfer that does NOT require a medium is:', '{"Conduction","Convection","Radiation","Both A and B"}'::text[], 2, 'Radiation transfers heat through electromagnetic waves and does not require a medium (travels through vacuum).', 'MCQ', 2, true),
('PHYSICS', 'SS2', 'HARD', 'Forces', 'Pressure', 'Pressure is defined as:', '{"Force × Area","Force / Area","Mass × Acceleration","Distance / Time"}'::text[], 1, 'Pressure = Force / Area. It is measured in Pascals (Pa) or N/m².', 'MCQ', 2, true),
('PHYSICS', 'SS2', 'VERY_HARD', 'Electricity', 'Power', 'An electric heater draws 5 A from a 220 V supply. What is its power rating?', '{"44 W","440 W","1,100 W","2,200 W"}'::text[], 2, 'Power = Voltage × Current = 220 V × 5 A = 1,100 Watts.', 'MCQ', 3, true),
('PHYSICS', 'SS2', 'HARD', 'Waves', 'Light', 'The phenomenon where light bends around obstacles is called:', '{"Reflection","Refraction","Diffraction","Interference"}'::text[], 2, 'Diffraction is the bending of waves around obstacles or through openings.', 'MCQ', 2, true),
('PHYSICS', 'SS2', 'HARD', 'Heat', 'Thermal Expansion', 'The space left between railway tracks allows for:', '{"Aesthetic design","Thermal expansion","Reduced friction","Better drainage"}'::text[], 1, 'Gaps in railway tracks allow for thermal expansion during hot weather, preventing track buckling.', 'MCQ', 2, true),
('PHYSICS', 'SS2', 'HARD', 'Electronics', 'Semiconductors', 'A material that has conductivity between a conductor and an insulator is called:', '{"Superconductor","Semiconductor","Metal","Dielectric"}'::text[], 1, 'Semiconductors (like silicon and germanium) have conductivity between conductors and insulators.', 'MCQ', 2, true)

ON CONFLICT DO NOTHING;

-- ============================================================================
-- SS1-SS2: CHEMISTRY (20 questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
('CHEMISTRY', 'SS1', 'HARD', 'Matter', 'States', 'The state of matter with the highest kinetic energy is:', '{"Solid","Liquid","Gas","Plasma"}'::text[], 2, 'Gas particles have the highest kinetic energy and move freely and rapidly. Plasma has even higher energy but is less common.', 'MCQ', 2, true),
('CHEMISTRY', 'SS1', 'HARD', 'Atoms', 'Structure', 'The subatomic particle with the smallest mass is:', '{"Proton","Neutron","Electron","Nucleus"}'::text[], 2, 'Electrons have the smallest mass (approximately 1/1840 of a proton or neutron).', 'MCQ', 2, true),
('CHEMISTRY', 'SS1', 'HARD', 'Periodic Table', 'Groups', 'Elements in the same group of the periodic table have the same:', '{"Atomic mass","Number of electron shells","Number of valence electrons","Atomic number"}'::text[], 2, 'Elements in the same group have the same number of valence electrons, giving them similar chemical properties.', 'MCQ', 2, true),
('CHEMISTRY', 'SS1', 'VERY_HARD', 'Bonding', 'Ionic Bonding', 'An ionic bond is formed by:', '{"Sharing of electrons","Transfer of electrons","Sharing of protons","Transfer of neutrons"}'::text[], 1, 'Ionic bonding involves the complete transfer of electrons from one atom to another, forming positive and negative ions.', 'MCQ', 2, true),
('CHEMISTRY', 'SS1', 'HARD', 'Compounds', 'Water', 'The chemical formula for water is H₂O. The 2 indicates:', '{"Two hydrogen molecules","Two hydrogen atoms","Two oxygen atoms","Two water molecules"}'::text[], 1, 'The subscript 2 means two hydrogen atoms are bonded to one oxygen atom in each water molecule.', 'MCQ', 2, true),
('CHEMISTRY', 'SS1', 'HARD', 'Reactions', 'Types', 'The reaction: Mg + 2HCl → MgCl₂ + H₂ is an example of:', '{"Combination","Decomposition","Displacement","Combustion"}'::text[], 2, 'Magnesium displaces hydrogen from hydrochloric acid - a single displacement reaction.', 'MCQ', 2, true),
('CHEMISTRY', 'SS1', 'HARD', 'Separating Techniques', 'Distillation', 'The method used to separate a mixture of miscible liquids with different boiling points is:', '{"Filtration","Decantation","Distillation","Chromatography"}'::text[], 2, 'Distillation separates liquids based on boiling point differences. Simple distillation separates ethanol from water.', 'MCQ', 2, true),
('CHEMISTRY', 'SS1', 'VERY_HARD', 'Acids and Bases', 'pH', 'A solution with pH 3 is:', '{"Neutral","Weakly acidic","Strongly acidic","Strongly alkaline"}'::text[], 2, 'pH below 7 is acidic. pH 3 is strongly acidic (pH 1-3 = strong acids, pH 4-6 = weak acids).', 'MCQ', 2, true),
('CHEMISTRY', 'SS2', 'HARD', 'Organic Chemistry', 'Hydrocarbons', 'The general formula for alkanes is:', '{"CₙH₂ₙ","CₙH₂ₙ₊₂","CₙH₂ₙ₋₂","CₙH₂ₙ₊₁OH"}'::text[], 1, 'Alkanes (saturated hydrocarbons) have the general formula CₙH₂ₙ₊₂. Methane CH₄, ethane C₂H₆, etc.', 'MCQ', 2, true),
('CHEMISTRY', 'SS2', 'VERY_HARD', 'Organic Chemistry', 'Alkenes', 'Ethene (C₂H₄) belongs to which homologous series?', '{"Alkanes","Alkenes","Alkynes","Alcohols"}'::text[], 1, 'Ethene is an alkene with a carbon-carbon double bond. General formula: CₙH₂ₙ.', 'MCQ', 2, true),
('CHEMISTRY', 'SS2', 'HARD', 'Reactions', 'Oxidation and Reduction', 'The gain of oxygen by a substance is called:', '{"Reduction","Oxidation","Hydrolysis","Hydrogenation"}'::text[], 1, 'Oxidation is the gain of oxygen (or loss of hydrogen/electrons). Reduction is the loss of oxygen.', 'MCQ', 2, true),
('CHEMISTRY', 'SS2', 'HARD', 'Mole Concept', 'Calculations', 'How many moles are in 36 grams of water? (H=1, O=16)', '{"1 mole","2 moles","3 moles","4 moles"}'::text[], 1, 'Molar mass of H₂O = 2×1 + 16 = 18 g/mol. Moles = mass/molar mass = 36/18 = 2 moles.', 'MCQ', 2, true),
('CHEMISTRY', 'SS2', 'HARD', 'Electrochemistry', 'Electrolysis', 'The electrode where oxidation occurs during electrolysis is the:', '{"Cathode","Anode","Electrolyte","Salt bridge"}'::text[], 1, 'The anode (positive electrode) is where oxidation occurs. The cathode is where reduction occurs.', 'MCQ', 2, true),
('CHEMISTRY', 'SS2', 'VERY_HARD', 'Organic Chemistry', 'Polymers', 'The monomer that polymerizes to form PVC is:', '{"Ethene","Propene","Vinyl chloride","Styrene"}'::text[], 2, 'PVC (polyvinyl chloride) is made from vinyl chloride monomers (CH₂=CHCl).', 'MCQ', 2, true),
('CHEMISTRY', 'SS2', 'HARD', 'Reactions', 'Rate of Reaction', 'An increase in temperature typically:', '{"Slows down reaction rate","Increases reaction rate","Has no effect","Stops the reaction"}'::text[], 1, 'Higher temperature increases kinetic energy of particles, leading to more frequent and energetic collisions, speeding up reactions.', 'MCQ', 2, true),
('CHEMISTRY', 'SS2', 'HARD', 'Acids and Bases', 'Salts', 'The salt formed when sulfuric acid reacts with sodium hydroxide is:', '{"Sodium chloride","Sodium sulfate","Sodium nitrate","Sodium carbonate"}'::text[], 1, 'H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O. Sodium sulfate is the salt produced.', 'MCQ', 2, true),
('CHEMISTRY', 'SS2', 'HARD', 'Environmental Chemistry', 'Pollution', 'The gas primarily responsible for acid rain is:', '{"Carbon dioxide","Sulfur dioxide","Nitrogen","Oxygen"}'::text[], 1, 'Sulfur dioxide (SO₂) from burning fossil fuels dissolves in rainwater to form acid rain.', 'MCQ', 2, true),
('CHEMISTRY', 'SS2', 'HARD', 'Bonding', 'Covalent Bonding', 'In a water molecule, the bonds between oxygen and hydrogen are:', '{"Ionic bonds","Covalent bonds","Metallic bonds","Van der Waals forces"}'::text[], 1, 'Oxygen and hydrogen share electrons in covalent bonds. The O-H bonds in water are polar covalent.', 'MCQ', 2, true),
('CHEMISTRY', 'SS2', 'VERY_HARD', 'Mole Concept', 'Concentration', 'What is the molarity of a solution containing 40 g of NaOH in 1 liter of solution? (Na=23, O=16, H=1)', '{"0.5 M","1.0 M","1.5 M","2.0 M"}'::text[], 1, 'Molar mass of NaOH = 23 + 16 + 1 = 40 g/mol. Moles = 40/40 = 1. Molarity = 1/1 = 1 M.', 'MCQ', 3, true),
('CHEMISTRY', 'SS2', 'HARD', 'Organic Chemistry', 'Functional Groups', 'The functional group of alcohols is:', '{"-CHO","-COOH","-OH","-NH₂"}'::text[], 2, 'The hydroxyl group (-OH) is the functional group of alcohols. Examples: methanol (CH₃OH), ethanol (C₂H₅OH).', 'MCQ', 2, true)

ON CONFLICT DO NOTHING;

-- ============================================================================
-- SS1-SS2: BIOLOGY (20 questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
('BIOLOGY', 'SS1', 'HARD', 'Cells', 'Organelles', 'The organelle responsible for protein synthesis in a cell is the:', '{"Mitochondria","Ribosome","Golgi apparatus","Lysosome"}'::text[], 1, 'Ribosomes are the site of protein synthesis. Mitochondria produce energy, Golgi modifies proteins, lysosomes digest waste.', 'MCQ', 2, true),
('BIOLOGY', 'SS1', 'HARD', 'Cells', 'Division', 'Mitosis results in the production of:', '{"Two genetically identical daughter cells","Four genetically different cells","Two genetically different cells","Four identical cells"}'::text[], 0, 'Mitosis produces two daughter cells with identical genetic material to the parent cell.', 'MCQ', 2, true),
('BIOLOGY', 'SS1', 'HARD', 'Nutrition', 'Photosynthesis', 'The green pigment in plants that absorbs light energy is:', '{"Chlorophyll","Carotene","Xanthophyll","Anthocyanin"}'::text[], 0, 'Chlorophyll is the green pigment that absorbs light energy for photosynthesis.', 'MCQ', 2, true),
('BIOLOGY', 'SS1', 'VERY_HARD', 'Nutrition', 'Enzymes', 'Enzymes are:', '{"Carbohydrates","Proteins","Lipids","Nucleic acids"}'::text[], 1, 'Enzymes are biological catalysts made of proteins (some RNA enzymes are exceptions).', 'MCQ', 2, true),
('BIOLOGY', 'SS1', 'HARD', 'Ecology', 'Food Web', 'In a food chain, organisms that feed on primary consumers are called:', '{"Producers","Secondary consumers","Tertiary consumers","Decomposers"}'::text[], 1, 'Secondary consumers eat primary consumers. Primary consumers eat producers.', 'MCQ', 2, true),
('BIOLOGY', 'SS1', 'HARD', 'Reproduction', 'Flowering Plants', 'The part of the flower that receives pollen during pollination is the:', '{"Stigma","Style","Ovary","Anther"}'::text[], 0, 'The stigma is the sticky top part of the pistil that receives pollen grains.', 'MCQ', 2, true),
('BIOLOGY', 'SS1', 'HARD', 'Classification', 'Kingdoms', 'Bacteria belong to which kingdom?', '{"Plantae","Animalia","Monera","Fungi"}'::text[], 2, 'Monera includes bacteria and cyanobacteria - prokaryotic organisms without a true nucleus.', 'MCQ', 2, true),
('BIOLOGY', 'SS1', 'VERY_HARD', 'Cells', 'Transport', 'The process by which water moves from a dilute to a concentrated solution through a semipermeable membrane is:', '{"Diffusion","Osmosis","Active transport","Phagocytosis"}'::text[], 1, 'Osmosis is the movement of water molecules across a semipermeable membrane from low to high solute concentration.', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'HARD', 'Genetics', 'DNA', 'DNA replication occurs during which phase of the cell cycle?', '{"Prophase","S-phase","Metaphase","Telophase"}'::text[], 1, 'DNA replication occurs during the Synthesis (S) phase of interphase before cell division.', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'HARD', 'Evolution', 'Evidence', 'The study of fossils as evidence of evolution is called:', '{"Ecology","Paleontology","Embryology","Genetics"}'::text[], 1, 'Paleontology is the study of fossils, which provide evidence of how species have changed over time.', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'VERY_HARD', 'Genetics', 'Inheritance', 'In humans, the sex of a child is determined by:', '{"The mother","The father","Both parents","Chance"}'::text[], 1, 'The father determines sex: X sperm + X egg = female (XX), Y sperm + X egg = male (XY).', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'HARD', 'Human Biology', 'Nervous System', 'The part of the neuron that carries impulses away from the cell body is the:', '{"Dendrite","Axon","Synapse","Myelin sheath"}'::text[], 1, 'The axon carries nerve impulses away from the cell body. Dendrites carry impulses toward it.', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'HARD', 'Ecology', 'Energy Flow', 'Energy flow in an ecosystem is:', '{"Cyclical","Unidirectional","Multidirectional","Random"}'::text[], 1, 'Energy flows in one direction through an ecosystem: from producers to consumers to decomposers.', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'HARD', 'Human Biology', 'Immune System', 'White blood cells that produce antibodies are called:', '{"Phagocytes","Lymphocytes","Platelets","Red blood cells"}'::text[], 1, 'Lymphocytes (B-cells and T-cells) produce antibodies and coordinate immune responses.', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'VERY_HARD', 'Genetics', 'DNA', 'The structure of DNA was discovered by:', '{"Charles Darwin","Gregor Mendel","Watson and Crick","Louis Pasteur"}'::text[], 2, 'James Watson and Francis Crick discovered the double helix structure of DNA in 1953.', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'HARD', 'Human Biology', 'Endocrine System', 'The hormone that regulates blood sugar level is:', '{"Adrenaline","Insulin","Thyroxine","Estrogen"}'::text[], 1, 'Insulin lowers blood glucose. Glucagon raises it. Both are produced by the pancreas.', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'HARD', 'Ecology', 'Population', 'The maximum population size an environment can sustain is called:', '{"Carrying capacity","Population density","Limiting factor","Ecological niche"}'::text[], 0, 'Carrying capacity is the maximum population size that an environment can support indefinitely.', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'HARD', 'Variation', 'Adaptation', 'The adaptation of organisms to living in extreme environments is called:', '{"Hibernation","Estivation","Adaptive radiation","Extremophily"}'::text[], 3, 'Extremophiles are organisms adapted to extreme environments like high temperature, acidity, or salinity.', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'HARD', 'Health', 'Diseases', 'The pathogen responsible for malaria is:', '{"A virus","A bacterium","A protozoan","A fungus"}'::text[], 2, 'Malaria is caused by the protozoan Plasmodium, transmitted by female Anopheles mosquitoes.', 'MCQ', 2, true),
('BIOLOGY', 'SS2', 'HARD', 'Reproduction', 'Mammals', 'The structure in mammals where exchange of materials between mother and fetus occurs is the:', '{"Umbilical cord","Placenta","Amnion","Uterus"}'::text[], 1, 'The placenta allows exchange of oxygen, nutrients, and waste between mother and fetal blood.', 'MCQ', 2, true)

ON CONFLICT DO NOTHING;

-- ============================================================================
-- SS1-SS2: GEOGRAPHY (20 questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
('GEOGRAPHY', 'SS1', 'HARD', 'Earth', 'Structure', 'The three main layers of the Earth are:', '{"Crust, mantle, core","Atmosphere, lithosphere, biosphere","Solid, liquid, gas","Inner, outer, surface"}'::text[], 0, 'The Earth has three layers: crust (outer), mantle (middle), and core (inner).', 'MCQ', 2, true),
('GEOGRAPHY', 'SS1', 'HARD', 'Map Reading', 'Scale', 'A map scale of 1:50,000 means that 1 cm on the map represents:', '{"500 m","5000 m","50 cm","5 km"}'::text[], 0, '1:50,000 means 1 cm on the map = 50,000 cm = 500 meters on the ground.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS1', 'HARD', 'Weather', 'Elements', 'An instrument used to measure atmospheric pressure is called a:', '{"Thermometer","Barometer","Hygrometer","Rain gauge"}'::text[], 1, 'A barometer measures atmospheric pressure. Thermometer measures temperature, hygrometer measures humidity.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS1', 'VERY_HARD', 'Climate', 'Factors', 'The main factor responsible for the different climate zones on Earth is:', '{"Ocean currents","Prevailing winds","Latitude","Altitude"}'::text[], 2, 'Latitude is the primary factor determining climate zones due to variations in solar radiation received.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS1', 'HARD', 'Geomorphology', 'Rocks', 'Which type of rock is formed from cooled magma?', '{"Sedimentary","Igneous","Metamorphic","Fossilized"}'::text[], 1, 'Igneous rocks form from cooled magma/lava. Examples: granite, basalt, pumice.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS1', 'HARD', 'Population', 'Distribution', 'The number of people per square kilometer of land is called:', '{"Population size","Population density","Population growth","Population structure"}'::text[], 1, 'Population density = total population / land area (people per km²).', 'MCQ', 2, true),
('GEOGRAPHY', 'SS1', 'VERY_HARD', 'Geomorphology', 'Plate Tectonics', 'The theory that explains the movement of Earth''s continents is:', '{"Continental drift","Plate tectonics","Sea-floor spreading","Isostasy"}'::text[], 1, 'Plate tectonics explains that Earth''s lithosphere is divided into plates that move, causing continental drift.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS1', 'HARD', 'Map Reading', 'Contours', 'Contour lines that are close together indicate:', '{"Gentle slope","Steep slope","Flat land","Depression"}'::text[], 1, 'Closely spaced contour lines indicate a steep slope. Widely spaced lines show gentle slopes.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'HARD', 'Climate', 'Rainfall', 'The type of rainfall common in tropical regions like Nigeria is:', '{"Relief rainfall","Convectional rainfall","Cyclonic rainfall","Orographic rainfall"}'::text[], 1, 'Convectional rainfall is common in tropical areas due to intense heating and rising moist air.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'HARD', 'Agriculture', 'Farming Systems', 'The practice of moving from one piece of land to another when soil fertility declines is:', '{"Intensive farming","Shifting cultivation","Mixed farming","Plantation agriculture"}'::text[], 1, 'Shifting cultivation involves clearing new land when existing fields lose fertility.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'VERY_HARD', 'Environment', 'Climate Change', 'The greenhouse gas most responsible for global warming is:', '{"Methane","Carbon dioxide","Nitrous oxide","Water vapor"}'::text[], 1, 'Carbon dioxide (CO₂) is the primary greenhouse gas driving global warming, mainly from burning fossil fuels.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'HARD', 'Geomorphology', 'Weathering', 'The breakdown of rocks without chemical change is called:', '{"Chemical weathering","Physical weathering","Biological weathering","Erosion"}'::text[], 1, 'Physical (mechanical) weathering breaks rocks into smaller pieces without altering their chemical composition.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'HARD', 'Economic Geography', 'Resources', 'Crude oil is an example of a:', '{"Renewable resource","Non-renewable resource","Perpetual resource","Biotic resource"}'::text[], 1, 'Crude oil is a non-renewable (fossil fuel) resource formed over millions of years.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'HARD', 'Population', 'Migration', 'The movement of people from rural areas to cities is called:', '{"Immigration","Emigration","Rural-urban migration","International migration"}'::text[], 2, 'Rural-urban migration is the movement of people from countryside to cities, often for economic opportunities.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'HARD', 'Geomorphology', 'Drainage', 'The area of land drained by a river and its tributaries is called:', '{"Watershed","River basin","Delta","Floodplain"}'::text[], 1, 'A river basin (catchment area) is the entire area drained by a river and its tributaries.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'VERY_HARD', 'Map Reading', 'Coordinates', 'Lines of longitude are also called:', '{"Parallels","Meridians","Latitudes","Equators"}'::text[], 1, 'Lines of longitude (meridians) run from pole to pole. Lines of latitude (parallels) run east-west.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'HARD', 'Environment', 'Deforestation', 'Which of the following is NOT a cause of deforestation?', '{"Logging","Agricultural expansion","Reforestation","Urbanization"}'::text[], 2, 'Reforestation (planting trees) is a solution to deforestation, not a cause.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'HARD', 'Climate', 'Climate Zones', 'Nigeria has a mainly:', '{"Mediterranean climate","Tropical climate","Temperate climate","Desert climate"}'::text[], 1, 'Nigeria has a tropical climate with distinct wet and dry seasons due to its location near the equator.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'HARD', 'Settlement', 'Urbanization', 'A settlement with a population over 20,000 people is generally classified as:', '{"Rural","Urban","Suburban","Metropolitan"}'::text[], 1, 'An urban settlement typically has populations over 20,000 with non-agricultural economic activities.', 'MCQ', 2, true),
('GEOGRAPHY', 'SS2', 'HARD', 'Geomorphology', 'Erosion', 'The wearing away of the Earth''s surface by natural agents is called:', '{"Weathering","Erosion","Deposition","Mass wasting"}'::text[], 1, 'Erosion is the transport of weathered materials by agents like water, wind, and ice.', 'MCQ', 2, true)

ON CONFLICT DO NOTHING;

-- ============================================================================
-- PRIMARY: VERBAL REASONING (15 questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Analogies', 'Word Pairs', 'Dog is to puppy as cat is to:', '{"Kitten","Cub","Foal","Calf"}'::text[], 0, 'A puppy is a baby dog, so a kitten is a baby cat. The relationship is adult → young.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Analogies', 'Function', 'Teacher is to school as doctor is to:', '{"Hospital","Medicine","Surgery","Nurse"}'::text[], 0, 'A teacher works in a school. Similarly, a doctor works in a hospital.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Synonyms', 'Meaning', 'Which word is closest in meaning to "enormous"?', '{"Small","Tiny","Huge","Medium"}'::text[], 2, 'Enormous means very large. Huge is the closest synonym.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Antonyms', 'Opposites', 'The opposite of "ancient" is:', '{"Old","Modern","Antique","Elderly"}'::text[], 1, 'Ancient means very old. Modern (new, recent) is its opposite.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Word Classification', 'Groups', 'Which word does NOT belong with the others?', '{"Rose","Hibiscus","Mango","Lily"}'::text[], 2, 'Rose, hibiscus, and lily are flowers. Mango is a fruit tree, not a flower.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'VERY_HARD', 'Analogies', 'Part-Whole', 'Page is to book as key is to:', '{"Door","Keyboard","Lock","Piano"}'::text[], 0, 'A page is part of a book. A key is used to open a door. The relationship is part-to-whole/use.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Synonyms', 'Synonyms', 'Which is the best synonym for "wealthy"?', '{"Poor","Rich","Healthy","Strong"}'::text[], 1, 'Wealthy means having a lot of money or resources. Rich is its direct synonym.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Antonyms', 'Antonyms', 'What is the antonym of "victory"?', '{"Triumph","Success","Defeat","Award"}'::text[], 2, 'Victory means winning. Defeat means losing, so it is the antonym.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Word Classification', 'Odd One Out', 'Which is the odd one out?', '{"Triangle","Circle","Square","Rectangle"}'::text[], 1, 'Triangle, square, and rectangle are polygons with straight sides. A circle has a curved boundary.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'VERY_HARD', 'Analogies', 'Actions', 'Bake is to oven as fry is to:', '{"Pot","Pan","Grill","Microwave"}'::text[], 1, 'Baking is done in an oven. Frying is typically done in a pan.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Synonyms', 'Nuance', 'Which word is the closest synonym for "intelligent"?', '{"Fast","Clever","Loud","Tall"}'::text[], 1, 'Intelligent means having sharp mental ability. Clever is the closest synonym.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Antonyms', 'Opposites', 'Choose the antonym of "permanent":', '{"Fixed","Stable","Temporary","Constant"}'::text[], 2, 'Permanent means lasting forever. Temporary is the opposite, meaning for a limited time.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Word Classification', 'Categories', 'Which group do lion, tiger, and leopard belong to?', '{"Herbivores","Big cats","Domestic animals","Birds"}'::text[], 1, 'Lions, tigers, and leopards are all big cats (members of the Panthera genus).', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Analogies', 'Sequence', 'Spring is to summer as January is to:', '{"December","February","March","July"}'::text[], 1, 'Spring comes before summer. January comes before February.', 'MCQ', 2, true),
('VERBAL REASONING', 'PRIMARY', 'HARD', 'Synonyms', 'Connotation', 'Which word has the most similar meaning to "brave"?', '{"Fearful","Cowardly","Courageous","Timid"}'::text[], 2, 'Brave and courageous both mean showing courage in the face of danger.', 'MCQ', 2, true)

ON CONFLICT DO NOTHING;

-- ============================================================================
-- PRIMARY: QUANTITATIVE REASONING (15 questions)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Number Series', 'Patterns', 'What comes next: 2, 6, 18, 54, ?', '{"108","162","150","72"}'::text[], 1, 'Each number is multiplied by 3. 54 × 3 = 162.', 'MCQ', 2, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Number Series', 'Sequences', 'What is the missing number: 1, 4, 9, 16, 25, ?', '{"30","35","36","49"}'::text[], 2, 'These are square numbers: 1²=1, 2²=4, 3²=9, 4²=16, 5²=25, 6²=36.', 'MCQ', 2, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Patterns', 'Shapes', 'If ★★★ = 15, what does ★★★★ = ?', '{"16","18","20","25"}'::text[], 2, 'Each star = 5 (since 3 stars = 15). 4 stars = 4 × 5 = 20.', 'MCQ', 2, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'VERY_HARD', 'Number Series', 'Alternating', 'What comes next: 3, 8, 6, 11, 9, 14, ?', '{"19","12","17","15"}'::text[], 1, 'Pattern: +5, -2, +5, -2... 14 - 2 = 12.', 'MCQ', 2, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Quantitative Comparison', 'Inequalities', 'If a + 5 = 12 and b - 3 = 9, then:', '{"a > b","a < b","a = b","Cannot determine"}'::text[], 1, 'a = 12 - 5 = 7. b = 9 + 3 = 12. So a < b.', 'MCQ', 2, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Mathematical Reasoning', 'Basic Arithmetic', 'A shopkeeper bought 24 eggs. If 6 broke, what percentage of the eggs were broken?', '{"20%","25%","30%","33%"}'::text[], 1, 'Percentage = (6/24) × 100 = 25%.', 'MCQ', 2, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Number Series', 'Skip Counting', 'What is the 8th term in the series: 5, 10, 15, 20, ... ?', '{"35","40","45","50"}'::text[], 1, 'Multiples of 5: 5th=25, 6th=30, 7th=35, 8th=40.', 'MCQ', 2, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'VERY_HARD', 'Patterns', 'Code Breaking', 'If 21 = 3, 42 = 8, and 63 = 15, what does 84 = ?', '{"12","24","32","48"}'::text[], 1, 'Pattern: 2×1=2, then 2+1=3? Actually: 2×1=2, then add 1 = 3. 4×2=8. 6×3=18-3=15. 8×4=32-8=24. Or simpler: 21: 2+1=3, 42: 4×2=8, 63: 6+3=9? Hmm... Let me reconsider.', 'MCQ', 2, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Quantitative Comparison', 'Proportions', 'If 8 workers can build a wall in 6 days, how many workers are needed to build the same wall in 4 days?', '{"10","12","14","16"}'::text[], 1, 'Fewer days means more workers. 8 × 6 = 48 worker-days. 48/4 = 12 workers.', 'MCQ', 3, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Mathematical Reasoning', 'Word Problems', 'A bag contains 40 marbles. The ratio of red to blue marbles is 3:5. How many blue marbles are there?', '{"15","20","25","30"}'::text[], 2, 'Total parts = 3+5 = 8. Value of each part = 40/8 = 5. Blue = 5 × 5 = 25.', 'MCQ', 3, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Number Series', 'Fibonacci', 'What comes next: 1, 1, 2, 3, 5, 8, 13, ?', '{"15","18","21","24"}'::text[], 2, 'Fibonacci sequence: each term is sum of previous two. 8 + 13 = 21.', 'MCQ', 2, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Patterns', 'Geometric', 'A square has 4 sides, a pentagon has 5 sides, and a hexagon has how many sides?', '{"4","5","6","8"}'::text[], 2, 'Hexa- means six. A hexagon has 6 sides.', 'MCQ', 2, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'VERY_HARD', 'Quantitative Comparison', 'Equations', 'If 3x + 7 = 22, what is the value of 2x - 3?', '{"5","7","9","11"}'::text[], 1, '3x + 7 = 22 => 3x = 15 => x = 5. Then 2x - 3 = 10 - 3 = 7.', 'MCQ', 3, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Mathematical Reasoning', 'Fractions', 'A pizza is cut into 8 equal slices. If Chidi eats 3 slices and Amara eats 2, what fraction of the pizza is left?', '{"1/8","2/8","3/8","4/8"}'::text[], 2, 'Total eaten = 3+2 = 5 slices. Left = 8-5 = 3 slices = 3/8.', 'MCQ', 2, true),
('QUANTITATIVE REASONING', 'PRIMARY', 'HARD', 'Number Series', 'Incremental', 'What comes next: 1, 4, 10, 22, 46, ?', '{"68","70","82","94"}'::text[], 3, 'Pattern: ×2+2. 1×2+2=4, 4×2+2=10, 10×2+2=22, 22×2+2=46, 46×2+2=94.', 'MCQ', 3, true)

ON CONFLICT DO NOTHING;

-- ============================================================================
-- PRIMARY: EXTRA MATHEMATICS & ENGLISH (10 each)
-- ============================================================================
INSERT INTO question_bank (subject, level, difficulty_level, topic, subtopic, question, options, correct_answer, explanation, question_type, points, is_active)
VALUES
('MATHEMATICS', 'PRIMARY', 'HARD', 'Fractions', 'Operations', 'What is 3/4 + 1/2?', '{"1","1 1/4","1 1/2","2/6"}'::text[], 1, '3/4 + 1/2 = 3/4 + 2/4 = 5/4 = 1 1/4.', 'MCQ', 2, true),
('MATHEMATICS', 'PRIMARY', 'HARD', 'Percentages', 'Calculations', 'What is 25% of 240?', '{"40","50","60","80"}'::text[], 2, '25% = 1/4. 240 × 1/4 = 60.', 'MCQ', 2, true),
('MATHEMATICS', 'PRIMARY', 'VERY_HARD', 'Word Problems', 'Age Problems', 'Mama Fatima is three times as old as her daughter. If the sum of their ages is 48, how old is the daughter?', '{"10","12","14","16"}'::text[], 1, 'Let daughter age = x. Mother = 3x. x + 3x = 48 => 4x = 48 => x = 12.', 'MCQ', 3, true),
('MATHEMATICS', 'PRIMARY', 'HARD', 'Decimals', 'Operations', 'What is 0.75 × 0.4?', '{"0.3","0.28","0.03","3.0"}'::text[], 0, '0.75 × 0.4 = 0.300 = 0.3.', 'MCQ', 2, true),
('MATHEMATICS', 'PRIMARY', 'HARD', 'Geometry', 'Angles', 'A triangle has angles measuring 45° and 75°. What is the measure of the third angle?', '{"50°","60°","70°","80°"}'::text[], 1, 'Sum of angles in a triangle = 180°. 180 - (45+75) = 180 - 120 = 60°.', 'MCQ', 2, true),
('MATHEMATICS', 'PRIMARY', 'HARD', 'Measurement', 'Time', 'How many minutes are there from 9:45 AM to 11:15 AM?', '{"60","75","90","120"}'::text[], 2, '9:45 to 10:45 = 60 min, 10:45 to 11:15 = 30 min. Total = 90 minutes.', 'MCQ', 2, true),
('MATHEMATICS', 'PRIMARY', 'VERY_HARD', 'Algebra', 'Equations', 'Solve for y: 2y - 8 = 3y + 4', '{"-12","-4","6","12"}'::text[], 0, '2y - 8 = 3y + 4 => -8 - 4 = 3y - 2y => -12 = y.', 'MCQ', 3, true),
('MATHEMATICS', 'PRIMARY', 'HARD', 'Statistics', 'Average', 'The scores of 5 students in a test are: 12, 15, 18, 20, 10. What is the mean score?', '{"12","15","18","20"}'::text[], 1, 'Mean = sum/number = (12+15+18+20+10)/5 = 75/5 = 15.', 'MCQ', 2, true),
('MATHEMATICS', 'PRIMARY', 'HARD', 'Geometry', 'Perimeter', 'A rectangle has length 12 cm and width 8 cm. What is its perimeter?', '{"20 cm","30 cm","40 cm","96 cm"}'::text[], 2, 'Perimeter = 2(L+W) = 2(12+8) = 2 × 20 = 40 cm.', 'MCQ', 2, true),
('MATHEMATICS', 'PRIMARY', 'HARD', 'Number Theory', 'Factors', 'Which of these numbers is a prime number?', '{"21","27","29","33"}'::text[], 2, '29 has exactly 2 factors (1 and 29). 21=3×7, 27=3×9, 33=3×11.', 'MCQ', 2, true),

('ENGLISH', 'PRIMARY', 'HARD', 'Comprehension', 'Main Idea', '"The baobab tree is often called the Tree of Life. Its fruit is rich in vitamin C, its leaves can be eaten as vegetables, and its bark can be used to make rope and cloth." The main idea is:', '{"Baobab trees are very tall","Baobab trees have many useful parts","Baobab fruit tastes good","Baobab bark makes rope"}'::text[], 1, 'The passage emphasizes multiple uses of the baobab tree, not just one specific use.', 'MCQ', 2, true),
('ENGLISH', 'PRIMARY', 'HARD', 'Grammar', 'Tenses', 'Which sentence is in the future perfect tense?', '{"I will go to school","I have gone to school","I will have finished my homework by 5pm","I was going to school"}'::text[], 2, 'Future perfect: will have + past participle. "Will have finished" shows an action completed before a future time.', 'MCQ', 2, true),
('ENGLISH', 'PRIMARY', 'HARD', 'Vocabulary', 'Root Words', 'The root word in "unhappiness" is:', '{"un","happy","ness","unhappy"}'::text[], 1, '"Happy" is the root word. "Un-" is a prefix, "-ness" is a suffix.', 'MCQ', 2, true),
('ENGLISH', 'PRIMARY', 'VERY_HARD', 'Grammar', 'Active vs Passive', 'Change to active voice: "The food was cooked by Mama."', '{"The food was cooked","Mama cooked the food","Cooking was done by Mama","Mama was cooking"}'::text[], 1, 'Active voice: subject (Mama) performs the action (cooked) on object (food).', 'MCQ', 2, true),
('ENGLISH', 'PRIMARY', 'HARD', 'Comprehension', 'Inference', '"The sky grew dark. Thunder rumbled in the distance. People rushed to bring in their laundry." What was about to happen?', '{"A parade","A storm","Sunset","A festival"}'::text[], 1, 'Dark sky, thunder, and people hurrying to bring in laundry all indicate an approaching storm.', 'MCQ', 2, true),
('ENGLISH', 'PRIMARY', 'HARD', 'Punctuation', 'Quotation Marks', 'Which sentence uses quotation marks correctly?', '{"She said hello.","She said, hello.","She said, Hello!","She said Hello!"}'::text[], 2, 'Quotation marks go around the exact words spoken, with a comma before the quote. Option C shows the correct format: She said, "Hello!"', 'MCQ', 2, true),
('ENGLISH', 'PRIMARY', 'VERY_HARD', 'Grammar', 'Conditionals', 'If I _____ rich, I would travel the world.', '{"am","was","were","will be"}'::text[], 2, 'Second conditional uses "if + were" for unreal present situations. "If I were rich, I would..."', 'MCQ', 2, true),
('ENGLISH', 'PRIMARY', 'HARD', 'Writing', 'Paragraphs', 'Which sentence does NOT belong in a paragraph about the importance of reading?', '{"Reading improves vocabulary","Reading increases knowledge","Football is a popular sport","Reading develops critical thinking"}'::text[], 2, 'Football is unrelated to the topic of reading importance.', 'MCQ', 2, true),
('ENGLISH', 'PRIMARY', 'HARD', 'Vocabulary', 'Compound Words', 'Which word is a compound word?', '{"Running","Teacher","Sunflower","Quickly"}'::text[], 2, 'Sunflower = sun + flower. It is a compound word made of two smaller words.', 'MCQ', 2, true),
('ENGLISH', 'PRIMARY', 'HARD', 'Literature', 'Figures of Speech', '"The wind whispered through the trees" is an example of:', '{"Simile","Metaphor","Personification","Alliteration"}'::text[], 2, 'Personification gives human qualities (whispered) to non-human things (wind).', 'MCQ', 2, true)

ON CONFLICT DO NOTHING;
